In [145]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import sqlite3

In [146]:
pd.set_option("display.max_columns", 50)
customer_churn = pd.read_csv("../data/Telco_Customer_Churn.csv")
customer_churn.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,Yes,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [147]:
customer_churn.shape

(7043, 21)

In [148]:
customer_churn.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [149]:
customer_churn.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [150]:
customer_churn.select_dtypes(include=['number'])

      SeniorCitizen  tenure  MonthlyCharges
0                 0       1           29.85
1                 0      34           56.95
2                 0       2           53.85
3                 0      45           42.30
4                 0       2           70.70
...             ...     ...             ...
7038              0      24           84.80
7039              0      72          103.20
7040              0      11           29.60
7041              1       4           74.40
7042              0      66          105.65

[7043 rows x 3 columns]

In [151]:
customer_churn['TotalCharges'] = pd.to_numeric(customer_churn['TotalCharges'],errors='coerce')

In [152]:
customer_churn.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [153]:
customer_churn['SeniorCitizen'] = customer_churn['SeniorCitizen'].astype('object')

In [154]:
customer_churn.dtypes

customerID           object
gender               object
SeniorCitizen        object
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [155]:
boolean_columns = [col for col in customer_churn.columns if customer_churn[col].nunique()==2]
boolean_columns

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'PaperlessBilling',
 'Churn']

In [156]:
# Map each column based on its actual values
for col in boolean_columns:
    unique_vals = set(customer_churn[col].dropna().unique())
    if unique_vals.issubset({'Yes', 'No'}) or unique_vals.issubset({'Female','Male'}):  # Only map if values are Yes/No
        customer_churn[col] = customer_churn[col].map({'Yes': 1, 'No': 0,'Female':0,'Male':1})
    # Columns with 0/1 values are left unchanged

customer_churn[boolean_columns].head()

,gender,SeniorCitizen,Partner,Dependents,PhoneService,PaperlessBilling,Churn
0,0,0,1,0,0,1,0
1,1,0,0,0,1,0,0
2,1,0,0,0,1,1,1
3,1,0,0,0,0,0,0
4,0,0,0,0,1,1,1

In [157]:
customer_churn[boolean_columns].values

array([[0, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 0]], shape=(7043, 7), dtype=object)

In [158]:
customer_churn.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [159]:
customer_churn.dropna(inplace=True,axis=0)

In [160]:
customer_churn.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [161]:
customer_churn.drop(columns=['customerID'],inplace=True)
customer_churn.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [162]:
# Identify categorical variables for one-hot encoding
categorical_columns = customer_churn.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", categorical_columns)
print(f"Booleancolumns {boolean_columns}")
print(f"\nNumber of categorical columns: {len(categorical_columns)}")

# Check unique values in each categorical column
for col in categorical_columns:
    print(f"\n{col}: {customer_churn[col].nunique()} unique values")
    print(customer_churn[col].unique())

Categorical columns: ['SeniorCitizen', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']
Booleancolumns ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

Number of categorical columns: 11

SeniorCitizen: 2 unique values
[0 1]

MultipleLines: 3 unique values
['No phone service' 'No' 'Yes']

InternetService: 3 unique values
['DSL' 'Fiber optic' 'No']

OnlineSecurity: 3 unique values
['No' 'Yes' 'No internet service']

OnlineBackup: 3 unique values
['Yes' 'No' 'No internet service']

DeviceProtection: 3 unique values
['No' 'Yes' 'No internet service']

TechSupport: 3 unique values
['No' 'Yes' 'No internet service']

StreamingTV: 3 unique values
['No' 'Yes' 'No internet service']

StreamingMovies: 3 unique values
['No' 'Yes' 'No internet service']

Contract: 3 unique values
['Month-to-month' 'One year' 'Two year']

PaymentMethod: 4 unique values
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [163]:
# Check the current dtypes of boolean columns
print("Boolean columns dtypes:")
for col in boolean_columns:
    print(f"{col}: {customer_churn[col].dtype}")
    print(f"  Unique values: {customer_churn[col].unique()}")

Boolean columns dtypes:
gender: int64
  Unique values: [0 1]
SeniorCitizen: object
  Unique values: [0 1]
Partner: int64
  Unique values: [1 0]
Dependents: int64
  Unique values: [0 1]
PhoneService: int64
  Unique values: [0 1]
PaperlessBilling: int64
  Unique values: [1 0]
Churn: int64
  Unique values: [0 1]

In [164]:
# Apply one-hot encoding with numeric dtype
customer_churn_encoded = pd.get_dummies(customer_churn, columns=categorical_columns, drop_first=True, dtype=int)
customer_churn_encoded.head()

,gender,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,SeniorCitizen_1,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,1,29.85,29.85,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1,0,0,34,1,0,56.95,1889.50,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
2,1,0,0,2,1,1,53.85,108.15,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
3,1,0,0,45,0,0,42.30,1840.75,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0
4,0,0,0,2,1,1,70.70,151.65,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [165]:
# Check the shape after encoding
print(f"Original shape: {customer_churn.shape}")
print(f"After one-hot encoding: {customer_churn_encoded.shape}")
print(f"\nNew columns created: {customer_churn_encoded.shape[1] - customer_churn.shape[1]}")

Original shape: (7032, 20)
After one-hot encoding: (7032, 31)

New columns created: 11

In [166]:
# Verify all columns are numeric
print("Data types after encoding:")
print(customer_churn_encoded.dtypes.value_counts())

Data types after encoding:
int64      29
float64     2
Name: count, dtype: int64

In [167]:
# normalize columns 'tenure', 'MonthlyCharges', 'TotalCharges'
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
columns_to_normalize = ['tenure', 'MonthlyCharges', 'TotalCharges']
customer_churn_encoded[columns_to_normalize] = scaler.fit_transform(customer_churn_encoded[columns_to_normalize])
customer_churn_encoded.head()

,gender,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,SeniorCitizen_1,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.000000,0,1,0.115423,0.001275,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0.464789,1,0,0.385075,0.215867,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0.014085,1,1,0.354229,0.010310,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0.619718,0,0,0.239303,0.210241,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0.014085,1,1,0.521891,0.015330,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [168]:
# Create a complete preprocessing pipeline with custom transformer
import pickle 
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin

# Custom transformer for all the preprocessing steps
class CustomPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.boolean_columns = None
        
    def fit(self, X, y=None):
        # Identify boolean columns (columns with exactly 2 unique values)
        self.boolean_columns = [col for col in X.columns if X[col].nunique() == 2]
        return self
    
    def transform(self, X):
        X = X.copy()
        
        # 1. Convert TotalCharges to numeric
        if 'TotalCharges' in X.columns:
            X['TotalCharges'] = pd.to_numeric(X['TotalCharges'], errors='coerce')
        
        # 2. Convert SeniorCitizen to object type
        if 'SeniorCitizen' in X.columns:
            X['SeniorCitizen'] = X['SeniorCitizen'].astype('object')
        
        # 3. Map boolean columns (Yes/No, Female/Male) to 0/1
        for col in self.boolean_columns:
            if col in X.columns:
                unique_vals = set(X[col].dropna().unique())
                if unique_vals.issubset({'Yes', 'No'}):
                    X[col] = X[col].map({'Yes': 1, 'No': 0})
                elif unique_vals.issubset({'Female', 'Male'}):
                    X[col] = X[col].map({'Female': 0, 'Male': 1})
        
        # 4. DON'T drop missing values here - handle it separately to keep X and y aligned
        # X = X.dropna()  # REMOVED
        
        # 5. Drop customerID if exists
        if 'customerID' in X.columns:
            X = X.drop(columns=['customerID'])
        
        return X

# Define feature groups
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
# Categorical features will be determined after custom preprocessing

# Create the pipeline
preprocessing_pipeline = Pipeline([
    ('custom_preprocessing', CustomPreprocessor())
])

print("✅ Custom preprocessing pipeline created!")
print("\nThis pipeline will handle:")
print("  1. Convert TotalCharges to numeric")
print("  2. Convert SeniorCitizen to object")
print("  3. Map Yes/No and Female/Male to 0/1")
print("  4. Drop customerID column")
print("\nNote: NaN handling will be done before splitting to keep X and y aligned")

✅ Custom preprocessing pipeline created!

This pipeline will handle:
  1. Convert TotalCharges to numeric
  2. Convert SeniorCitizen to object
  3. Map Yes/No and Female/Male to 0/1
  4. Drop customerID column

Note: NaN handling will be done before splitting to keep X and y aligned

In [169]:
# Now create the complete pipeline with encoding and scaling
# Read fresh data to test the pipeline
customer_churn_test = pd.read_csv("../data/Telco_Customer_Churn.csv")

# Get categorical columns after custom preprocessing
temp_preprocessor = CustomPreprocessor()
temp_data = temp_preprocessor.fit_transform(customer_churn_test)
categorical_features = temp_data.select_dtypes(include=['object']).columns.tolist()

print(f"Categorical features for one-hot encoding: {categorical_features}")
print(f"Numerical features for scaling: {numerical_features}")

Categorical features for one-hot encoding: ['SeniorCitizen', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']
Numerical features for scaling: ['tenure', 'MonthlyCharges', 'TotalCharges']

In [170]:
# Complete pipeline with all transformations
complete_pipeline = Pipeline([
    ('custom_preprocessing', CustomPreprocessor()),
    ('column_transformer', ColumnTransformer(
        transformers=[
            ('num', MinMaxScaler(), numerical_features),
            ('cat', OneHotEncoder(drop='first', sparse_output=False), categorical_features)
        ],
        remainder='passthrough'  # Keep other columns (already encoded boolean columns)
    ))
])

print("✅ Complete pipeline created!")
print("\nPipeline steps:")
print("  1. Custom preprocessing (TotalCharges, boolean mapping, etc.)")
print("  2. MinMax scaling for numerical features")
print("  3. One-hot encoding for categorical features")
print("  4. Keep binary encoded features as-is")

✅ Complete pipeline created!

Pipeline steps:
  1. Custom preprocessing (TotalCharges, boolean mapping, etc.)
  2. MinMax scaling for numerical features
  3. One-hot encoding for categorical features
  4. Keep binary encoded features as-is

In [171]:
# Test the pipeline on fresh data
customer_churn_pipeline_test = pd.read_csv("../data/Telco_Customer_Churn.csv")

# Separate features and target
y = customer_churn_pipeline_test['Churn']
X = customer_churn_pipeline_test.drop(columns=['Churn'])

# Fit and transform
X_transformed = complete_pipeline.fit_transform(X)

print(f"Original shape: {X.shape}")
print(f"Transformed shape: {X_transformed.shape}")
print(f"✅ Pipeline successfully processed the data!")
print(f"\nFirst few rows of transformed data:")
print(X_transformed[:3])

Original shape: (7043, 20)
Transformed shape: (7043, 30)
✅ Pipeline successfully processed the data!

First few rows of transformed data:
[[0.01388889 0.11542289 0.0012751  0.         1.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         1.         0.         0.         1.        ]
 [0.47222222 0.38507463 0.21586661 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         1.         0.         0.         0.         0.
  0.         0.         1.         0.         0.         0.
  1.         1.         0.         0.         1.         0.        ]
 [0.02777778 0.35422886 0.01031041 0.         0.         0.
  0.         0.         0.         1.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  1.         1.         0.         0.         1.         1.        ]]

In [172]:
# Save the pipeline for later use
with open('../preprocessor_pipeline.pkl', 'wb') as f:
    pickle.dump(complete_pipeline, f)

print("✅ Pipeline saved as 'preprocessor_pipeline.pkl'")
print("\nYou can now use this pipeline to transform new data:")
print("  1. Load: pipeline = pickle.load(open('preprocessor_pipeline.pkl', 'rb'))")
print("  2. Transform: X_new_transformed = pipeline.transform(X_new)")

✅ Pipeline saved as 'preprocessor_pipeline.pkl'

You can now use this pipeline to transform new data:
  1. Load: pipeline = pickle.load(open('preprocessor_pipeline.pkl', 'rb'))
  2. Transform: X_new_transformed = pipeline.transform(X_new)

In [173]:
#saving data to sqlite database 
conn = sqlite3.connect('../data/customer_churn.db')
customer_churn_dataframe = pd.read_csv("../data/Telco_Customer_Churn.csv")
customer_churn_dataframe.to_sql('customer_churn', conn, if_exists='replace', index=False)
conn.close()

In [174]:
from sqlalchemy import create_engine 
from sqlalchemy import text

engine = create_engine('sqlite:///../data/customer_churn.db')
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM customer_churn LIMIT 5"))
    rows = result.fetchall()
    for row in rows:
        print(row)

('7590-VHVEG', 'Female', 0, 'Yes', 'No', 1, 'No', 'No phone service', 'DSL', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85', 'No')
('5575-GNVDE', 'Male', 0, 'No', 'No', 34, 'Yes', 'No', 'DSL', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'One year', 'No', 'Mailed check', 56.95, '1889.5', 'No')
('3668-QPYBK', 'Male', 0, 'No', 'No', 2, 'Yes', 'No', 'DSL', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Mailed check', 53.85, '108.15', 'Yes')
('7795-CFOCW', 'Male', 0, 'No', 'No', 45, 'No', 'No phone service', 'DSL', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'One year', 'No', 'Bank transfer (automatic)', 42.3, '1840.75', 'No')
('9237-HQITU', 'Female', 0, 'No', 'No', 2, 'Yes', 'No', 'Fiber optic', 'No', 'No', 'No', 'No', 'No', 'No', 'Month-to-month', 'Yes', 'Electronic check', 70.7, '151.65', 'Yes')

In [175]:
#return data from sqlite database as a dataframe the split the data then preprocess train and test data seperatley 

def load_data_from_db(db_path,table_name):
    engine =create_engine(f"sqlite:///{db_path}")
    with engine.connect() as connection:
        query = f"select * from {table_name}"
        df = pd.read_sql(query,connection)
    return df

In [176]:
customer_churn = load_data_from_db(db_path="../data/customer_churn.db",table_name="customer_churn")
customer_churn.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [177]:
# Drop NaN values BEFORE splitting to keep X and y aligned
customer_churn_clean = customer_churn.dropna()

# split data set into test and train 
from sklearn.model_selection import train_test_split

X = customer_churn_clean.drop(columns=['Churn'])
y = customer_churn_clean['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Dataset shape after removing NaN: {customer_churn_clean.shape}")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")

Dataset shape after removing NaN: (7043, 21)
X_train shape: (5634, 20)
X_test shape: (1409, 20)

In [178]:
X_train.head()
y_train

3738     No
3151     No
4860     No
3867     No
3810     No
       ...
6303     No
6227    Yes
4673    Yes
2710     No
5639     No
Name: Churn, Length: 5634, dtype: object

In [179]:
# Fit the pipeline on training data and transform both train and test
X_train_transformed = complete_pipeline.fit_transform(X_train)
X_test_transformed = complete_pipeline.transform(X_test)  # Only transform, don't fit!

print(f"X_train original shape: {X_train.shape}")
print(f"X_train transformed shape: {X_train_transformed.shape}")
print(f"\nX_test original shape: {X_test.shape}")
print(f"X_test transformed shape: {X_test_transformed.shape}")
print(f"\n✅ Data successfully transformed!")

X_train original shape: (5634, 20)
X_train transformed shape: (5634, 30)

X_test original shape: (1409, 20)
X_test transformed shape: (1409, 30)

✅ Data successfully transformed!

In [180]:
# Also transform the target variable (Churn: Yes/No to 1/0)
y_train_encoded = y_train.map({'Yes': 1, 'No': 0})
y_test_encoded = y_test.map({'Yes': 1, 'No': 0})

print(f"y_train shape: {y_train_encoded.shape}")
print(f"y_test shape: {y_test_encoded.shape}")
print(f"\nClass distribution in training set:")
print(y_train_encoded.value_counts(normalize=True))

y_train shape: (5634,)
y_test shape: (1409,)

Class distribution in training set:
Churn
0    0.734647
1    0.265353
Name: proportion, dtype: float64

In [189]:
#now training the model using XGBOOST and Optuna for hyperparameter tuning
import xgboost as xgb
import optuna
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def objective(trial):
    param = {
        'verbosity': 0,  # Reduce output noise
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'use_label_encoder': False,
        
        # Tree structure parameters - EXPANDED RANGE
        'max_depth': trial.suggest_int('max_depth', 4, 15),  # Deeper trees
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),  # Wider range
        'max_delta_step': trial.suggest_int('max_delta_step', 0, 10),  # Helps with imbalanced data
        
        # Learning parameters - MORE ESTIMATORS
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.3, log=True),  # Log scale
        'n_estimators': trial.suggest_int('n_estimators', 200, 2000),  # More trees
        
        # Sampling parameters - EXPANDED
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.6, 1.0),
        'colsample_bynode': trial.suggest_float('colsample_bynode', 0.6, 1.0),  # NEW
        
        # Regularization parameters - EXPANDED (FIXED: log=True requires low > 0)
        'reg_alpha': trial.suggest_float('reg_alpha', 0.001, 10.0, log=True),  # L1 - FIXED
        'reg_lambda': trial.suggest_float('reg_lambda', 0.001, 10.0, log=True),  # L2 - FIXED
        
        # Handle imbalanced data - CRITICAL FOR ACCURACY
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 10.0),
        
        # Additional parameters
        'grow_policy': trial.suggest_categorical('grow_policy', ['depthwise', 'lossguide']),
        'max_leaves': trial.suggest_int('max_leaves', 0, 256),  # For lossguide
        'max_bin': trial.suggest_int('max_bin', 128, 512),  # Histogram size
        
        'random_state': 42,
        'tree_method': 'hist',  # Faster training
        'enable_categorical': False
    }
    
    model = xgb.XGBClassifier(**param)
    model.fit(X_train_transformed, y_train_encoded, 
              eval_set=[(X_test_transformed, y_test_encoded)],
              verbose=False)
    
    # Get probabilities for AUC (better than binary predictions)
    y_pred_proba = model.predict_proba(X_test_transformed)[:, 1]
    y_pred = model.predict(X_test_transformed)
    
    # Calculate multiple metrics for comparison
    auc = roc_auc_score(y_test_encoded, y_pred_proba)
    accuracy = accuracy_score(y_test_encoded, y_pred)
    precision = precision_score(y_test_encoded, y_pred)
    recall = recall_score(y_test_encoded, y_pred)
    f1 = f1_score(y_test_encoded, y_pred)
    
    # Store additional metrics as trial attributes
    trial.set_user_attr('accuracy', accuracy)
    trial.set_user_attr('precision', precision)
    trial.set_user_attr('recall', recall)
    trial.set_user_attr('f1', f1)
    
    # Optimize for accuracy instead of AUC if you want higher accuracy
    # return accuracy  # Use this if you want to optimize for accuracy
    return auc  # Or keep AUC for better overall ranking

In [190]:
# Run the optimization with MORE TRIALS
study = optuna.create_study(direction='maximize', study_name='xgboost_churn')
study.optimize(objective, n_trials=100, show_progress_bar=True)  # Increased from 50 to 100

print("=" * 50)
print("OPTIMIZATION RESULTS")
print("=" * 50)
print(f"\nBest AUC: {study.best_value:.4f}")
print(f"\nBest hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

print(f"\nBest trial metrics:")
print(f"  Accuracy:  {study.best_trial.user_attrs['accuracy']:.4f}")
print(f"  Precision: {study.best_trial.user_attrs['precision']:.4f}")
print(f"  Recall:    {study.best_trial.user_attrs['recall']:.4f}")
print(f"  F1 Score:  {study.best_trial.user_attrs['f1']:.4f}")
print(f"  AUC:       {study.best_value:.4f}")

# Show top 5 trials by accuracy
print("\n" + "=" * 50)
print("TOP 5 TRIALS BY ACCURACY")
print("=" * 50)
trials_df = study.trials_dataframe()
trials_df = trials_df.sort_values('user_attrs_accuracy', ascending=False).head(5)
print(trials_df[['number', 'user_attrs_accuracy', 'user_attrs_precision', 'user_attrs_recall', 'user_attrs_f1', 'value']])

[I 2025-11-24 22:37:24,729] A new study created in memory with name: xgboost_churn
Best trial: 0. Best value: 0.842692:   1%|          | 1/100 [00:00<01:35,  1.04it/s]

[I 2025-11-24 22:37:25,693] Trial 0 finished with value: 0.8426916221033869 and parameters: {'max_depth': 9, 'min_child_weight': 8, 'gamma': 1.325753381652478, 'max_delta_step': 3, 'learning_rate': 0.024470774762296005, 'n_estimators': 322, 'subsample': 0.931159613876554, 'colsample_bytree': 0.8301313504709691, 'colsample_bylevel': 0.8117411708725282, 'colsample_bynode': 0.8903285778183699, 'reg_alpha': 0.0504718628669293, 'reg_lambda': 7.550020850004477, 'scale_pos_weight': 7.075069376750838, 'grow_policy': 'depthwise', 'max_leaves': 244, 'max_bin': 300}. Best is trial 0 with value: 0.8426916221033869.

Best trial: 1. Best value: 0.843168:   2%|▏         | 2/100 [00:01<01:13,  1.33it/s]

[I 2025-11-24 22:37:26,295] Trial 1 finished with value: 0.8431682554444704 and parameters: {'max_depth': 8, 'min_child_weight': 1, 'gamma': 3.2603367682408653, 'max_delta_step': 9, 'learning_rate': 0.04265071676236977, 'n_estimators': 475, 'subsample': 0.9129252071722052, 'colsample_bytree': 0.9895444051252255, 'colsample_bylevel': 0.9788325688322477, 'colsample_bynode': 0.6004306717652481, 'reg_alpha': 0.006608779868688582, 'reg_lambda': 0.027592438878234815, 'scale_pos_weight': 3.489388107376015, 'grow_policy': 'depthwise', 'max_leaves': 104, 'max_bin': 443}. Best is trial 1 with value: 0.8431682554444704.

Best trial: 1. Best value: 0.843168:   3%|▎         | 3/100 [00:03<02:11,  1.36s/it]

[I 2025-11-24 22:37:28,369] Trial 2 finished with value: 0.8111666537497739 and parameters: {'max_depth': 11, 'min_child_weight': 2, 'gamma': 2.0898656558803292, 'max_delta_step': 4, 'learning_rate': 0.12004820063226464, 'n_estimators': 1820, 'subsample': 0.7041679943718014, 'colsample_bytree': 0.9628082245144427, 'colsample_bylevel': 0.9495127069225509, 'colsample_bynode': 0.8886622123945782, 'reg_alpha': 0.009513864154738526, 'reg_lambda': 0.009524516996267178, 'scale_pos_weight': 3.1749279413073244, 'grow_policy': 'depthwise', 'max_leaves': 94, 'max_bin': 349}. Best is trial 1 with value: 0.8431682554444704.

Best trial: 3. Best value: 0.847942:   4%|▍         | 4/100 [00:05<02:16,  1.42s/it]

[I 2025-11-24 22:37:29,880] Trial 3 finished with value: 0.8479423389909323 and parameters: {'max_depth': 4, 'min_child_weight': 1, 'gamma': 4.303966482178674, 'max_delta_step': 4, 'learning_rate': 0.007437362586713984, 'n_estimators': 1099, 'subsample': 0.8591779160702662, 'colsample_bytree': 0.7197752436946583, 'colsample_bylevel': 0.9078572344366705, 'colsample_bynode': 0.70431899824652, 'reg_alpha': 1.3553035610297717, 'reg_lambda': 9.09385480089653, 'scale_pos_weight': 2.4614070343931997, 'grow_policy': 'depthwise', 'max_leaves': 27, 'max_bin': 289}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:   5%|▌         | 5/100 [00:07<02:51,  1.81s/it]

[I 2025-11-24 22:37:32,378] Trial 4 finished with value: 0.8375261567077423 and parameters: {'max_depth': 15, 'min_child_weight': 3, 'gamma': 1.502068962005203, 'max_delta_step': 9, 'learning_rate': 0.016735947736563967, 'n_estimators': 723, 'subsample': 0.6471875492668926, 'colsample_bytree': 0.7860080959088059, 'colsample_bylevel': 0.6919034163533747, 'colsample_bynode': 0.8432598404195405, 'reg_alpha': 0.06147085446534446, 'reg_lambda': 5.321404611994239, 'scale_pos_weight': 8.39546286180038, 'grow_policy': 'depthwise', 'max_leaves': 74, 'max_bin': 406}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:   6%|▌         | 6/100 [00:10<03:13,  2.06s/it]

[I 2025-11-24 22:37:34,929] Trial 5 finished with value: 0.8282569944974038 and parameters: {'max_depth': 14, 'min_child_weight': 5, 'gamma': 1.6658003147784606, 'max_delta_step': 5, 'learning_rate': 0.030614239722443634, 'n_estimators': 1106, 'subsample': 0.7389057017359163, 'colsample_bytree': 0.8826753397674685, 'colsample_bylevel': 0.7914815093553493, 'colsample_bynode': 0.9023134164438924, 'reg_alpha': 0.04001640650019193, 'reg_lambda': 0.1444031462886947, 'scale_pos_weight': 7.521491274666841, 'grow_policy': 'depthwise', 'max_leaves': 97, 'max_bin': 158}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:   7%|▋         | 7/100 [00:14<04:32,  2.93s/it]

[I 2025-11-24 22:37:39,653] Trial 6 finished with value: 0.846259267870521 and parameters: {'max_depth': 8, 'min_child_weight': 4, 'gamma': 1.5834654532088532, 'max_delta_step': 9, 'learning_rate': 0.003106124864437164, 'n_estimators': 1764, 'subsample': 0.630857761096548, 'colsample_bytree': 0.8821139151942624, 'colsample_bylevel': 0.855149389292467, 'colsample_bynode': 0.9770970162828264, 'reg_alpha': 0.7042662478696472, 'reg_lambda': 0.0057252543000529555, 'scale_pos_weight': 1.0483465314544023, 'grow_policy': 'depthwise', 'max_leaves': 113, 'max_bin': 403}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:   8%|▊         | 8/100 [00:17<04:30,  2.94s/it]

[I 2025-11-24 22:37:42,623] Trial 7 finished with value: 0.8151295564339043 and parameters: {'max_depth': 5, 'min_child_weight': 5, 'gamma': 1.8068834937739835, 'max_delta_step': 4, 'learning_rate': 0.13856049621090058, 'n_estimators': 1543, 'subsample': 0.8009733079759918, 'colsample_bytree': 0.8736177194350487, 'colsample_bylevel': 0.8963180961543816, 'colsample_bynode': 0.9538591592023756, 'reg_alpha': 0.7173439438376041, 'reg_lambda': 0.024111010405476203, 'scale_pos_weight': 9.911640787292878, 'grow_policy': 'lossguide', 'max_leaves': 130, 'max_bin': 355}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:   9%|▉         | 9/100 [00:19<03:46,  2.48s/it]

[I 2025-11-24 22:37:44,100] Trial 8 finished with value: 0.827022139554109 and parameters: {'max_depth': 8, 'min_child_weight': 7, 'gamma': 0.10606013605963638, 'max_delta_step': 2, 'learning_rate': 0.05686865874805781, 'n_estimators': 570, 'subsample': 0.8177537002318628, 'colsample_bytree': 0.8706924304332099, 'colsample_bylevel': 0.9545084000345191, 'colsample_bynode': 0.8070018593792578, 'reg_alpha': 0.0013268939581880868, 'reg_lambda': 6.346831223524662, 'scale_pos_weight': 2.319507936151512, 'grow_policy': 'depthwise', 'max_leaves': 35, 'max_bin': 294}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:  10%|█         | 10/100 [00:21<03:47,  2.52s/it]

[I 2025-11-24 22:37:46,713] Trial 9 finished with value: 0.8377832028727169 and parameters: {'max_depth': 7, 'min_child_weight': 10, 'gamma': 1.9611708843469933, 'max_delta_step': 5, 'learning_rate': 0.052836296592988885, 'n_estimators': 1440, 'subsample': 0.9289069730987249, 'colsample_bytree': 0.9961955402294946, 'colsample_bylevel': 0.9397472463047091, 'colsample_bynode': 0.783697889266279, 'reg_alpha': 0.009720471329507723, 'reg_lambda': 0.34633547565397954, 'scale_pos_weight': 8.51855070031042, 'grow_policy': 'lossguide', 'max_leaves': 186, 'max_bin': 215}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 3. Best value: 0.847942:  11%|█         | 11/100 [00:24<03:41,  2.49s/it]

[I 2025-11-24 22:37:49,116] Trial 10 finished with value: 0.8428362913017644 and parameters: {'max_depth': 4, 'min_child_weight': 1, 'gamma': 4.936367061630799, 'max_delta_step': 1, 'learning_rate': 0.0016856032432529425, 'n_estimators': 939, 'subsample': 0.9873360899902001, 'colsample_bytree': 0.6606859733847714, 'colsample_bylevel': 0.60239797514373, 'colsample_bynode': 0.6887285981970763, 'reg_alpha': 7.343348322988699, 'reg_lambda': 0.0013070788663505468, 'scale_pos_weight': 5.069395420969844, 'grow_policy': 'lossguide', 'max_leaves': 0, 'max_bin': 503}. Best is trial 3 with value: 0.8479423389909323.

Best trial: 11. Best value: 0.848702:  12%|█▏        | 12/100 [00:27<04:02,  2.76s/it]

[I 2025-11-24 22:37:52,494] Trial 11 finished with value: 0.848701852282415 and parameters: {'max_depth': 12, 'min_child_weight': 3, 'gamma': 3.5159495555698106, 'max_delta_step': 7, 'learning_rate': 0.004094832834764993, 'n_estimators': 1949, 'subsample': 0.8356007542954484, 'colsample_bytree': 0.7124703245759424, 'colsample_bylevel': 0.8393138462769671, 'colsample_bynode': 0.9970912160422295, 'reg_alpha': 0.850374489307246, 'reg_lambda': 1.154256111374819, 'scale_pos_weight': 1.1902991525886317, 'grow_policy': 'depthwise', 'max_leaves': 154, 'max_bin': 222}. Best is trial 11 with value: 0.848701852282415.

Best trial: 12. Best value: 0.848973:  13%|█▎        | 13/100 [00:29<03:44,  2.59s/it]

[I 2025-11-24 22:37:54,684] Trial 12 finished with value: 0.848973107029373 and parameters: {'max_depth': 12, 'min_child_weight': 3, 'gamma': 4.111770509099629, 'max_delta_step': 7, 'learning_rate': 0.006445298274149941, 'n_estimators': 1228, 'subsample': 0.8532193704035901, 'colsample_bytree': 0.6899092515761324, 'colsample_bylevel': 0.7607064656527944, 'colsample_bynode': 0.7138861434228602, 'reg_alpha': 0.8348347124813643, 'reg_lambda': 0.9306848864625633, 'scale_pos_weight': 1.6185513139389134, 'grow_policy': 'depthwise', 'max_leaves': 169, 'max_bin': 228}. Best is trial 12 with value: 0.848973107029373.

Best trial: 13. Best value: 0.849363:  14%|█▍        | 14/100 [00:32<03:44,  2.61s/it]

[I 2025-11-24 22:37:57,353] Trial 13 finished with value: 0.8493631971892841 and parameters: {'max_depth': 12, 'min_child_weight': 3, 'gamma': 3.3959951863828004, 'max_delta_step': 7, 'learning_rate': 0.006202713797956186, 'n_estimators': 1972, 'subsample': 0.8632962516357873, 'colsample_bytree': 0.6059499715585702, 'colsample_bylevel': 0.7445288609490236, 'colsample_bynode': 0.7274688863049, 'reg_alpha': 3.524159657657527, 'reg_lambda': 0.7959073381738331, 'scale_pos_weight': 1.065530336880211, 'grow_policy': 'depthwise', 'max_leaves': 178, 'max_bin': 208}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 13. Best value: 0.849363:  15%|█▌        | 15/100 [00:38<05:01,  3.54s/it]

[I 2025-11-24 22:38:03,055] Trial 14 finished with value: 0.8475651657237334 and parameters: {'max_depth': 12, 'min_child_weight': 3, 'gamma': 3.1485015375912786, 'max_delta_step': 7, 'learning_rate': 0.009633304515854738, 'n_estimators': 1397, 'subsample': 0.7501615473393618, 'colsample_bytree': 0.6082159452268516, 'colsample_bylevel': 0.7361467680074105, 'colsample_bynode': 0.7178592127126748, 'reg_alpha': 7.239472508103674, 'reg_lambda': 0.9441094388155771, 'scale_pos_weight': 4.873820570894167, 'grow_policy': 'lossguide', 'max_leaves': 203, 'max_bin': 161}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 13. Best value: 0.849363:  16%|█▌        | 16/100 [00:43<05:41,  4.06s/it]

[I 2025-11-24 22:38:08,314] Trial 15 finished with value: 0.8463122271306416 and parameters: {'max_depth': 13, 'min_child_weight': 6, 'gamma': 3.7784100437206445, 'max_delta_step': 7, 'learning_rate': 0.0010209374354394761, 'n_estimators': 1574, 'subsample': 0.8825487624914294, 'colsample_bytree': 0.6181773761697129, 'colsample_bylevel': 0.7310191454888861, 'colsample_bynode': 0.6365279843731835, 'reg_alpha': 0.23379827455583976, 'reg_lambda': 1.096235757083447, 'scale_pos_weight': 3.705961448068596, 'grow_policy': 'depthwise', 'max_leaves': 183, 'max_bin': 221}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 13. Best value: 0.849363:  17%|█▋        | 17/100 [00:46<05:02,  3.65s/it]

[I 2025-11-24 22:38:11,002] Trial 16 finished with value: 0.8463974786225426 and parameters: {'max_depth': 11, 'min_child_weight': 3, 'gamma': 2.7901575978064592, 'max_delta_step': 7, 'learning_rate': 0.008383157953856716, 'n_estimators': 1999, 'subsample': 0.9866109292262837, 'colsample_bytree': 0.6897040837871762, 'colsample_bylevel': 0.6486349719246871, 'colsample_bynode': 0.7507349829420928, 'reg_alpha': 2.522092076011116, 'reg_lambda': 0.2913103205667049, 'scale_pos_weight': 1.9743468915005886, 'grow_policy': 'depthwise', 'max_leaves': 237, 'max_bin': 132}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 13. Best value: 0.849363:  18%|█▊        | 18/100 [00:49<05:00,  3.66s/it]

[I 2025-11-24 22:38:14,693] Trial 17 finished with value: 0.8460280554909709 and parameters: {'max_depth': 10, 'min_child_weight': 4, 'gamma': 4.221980210460104, 'max_delta_step': 8, 'learning_rate': 0.0038133220366641297, 'n_estimators': 1272, 'subsample': 0.7670424629229781, 'colsample_bytree': 0.7497542088655076, 'colsample_bylevel': 0.7580114992270024, 'colsample_bynode': 0.6663552900055562, 'reg_alpha': 0.2313182073856727, 'reg_lambda': 2.185471468945689, 'scale_pos_weight': 6.324642190309361, 'grow_policy': 'depthwise', 'max_leaves': 150, 'max_bin': 264}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 13. Best value: 0.849363:  19%|█▉        | 19/100 [00:53<05:03,  3.75s/it]

[I 2025-11-24 22:38:18,650] Trial 18 finished with value: 0.8448978273786457 and parameters: {'max_depth': 15, 'min_child_weight': 2, 'gamma': 4.599503191833396, 'max_delta_step': 10, 'learning_rate': 0.011700257307165039, 'n_estimators': 840, 'subsample': 0.881708047252577, 'colsample_bytree': 0.6489224084723364, 'colsample_bylevel': 0.690096507218756, 'colsample_bynode': 0.742506362617093, 'reg_alpha': 2.5590172512632052, 'reg_lambda': 0.07150932008025217, 'scale_pos_weight': 4.627563147183215, 'grow_policy': 'lossguide', 'max_leaves': 215, 'max_bin': 196}. Best is trial 13 with value: 0.8493631971892841.

Best trial: 19. Best value: 0.8496:  20%|██        | 20/100 [00:58<05:30,  4.13s/it]

[I 2025-11-24 22:38:23,671] Trial 19 finished with value: 0.849599576325919 and parameters: {'max_depth': 13, 'min_child_weight': 6, 'gamma': 2.5749782164446278, 'max_delta_step': 6, 'learning_rate': 0.002190304719810043, 'n_estimators': 1649, 'subsample': 0.7023710933450351, 'colsample_bytree': 0.6554108215787152, 'colsample_bylevel': 0.774796159817296, 'colsample_bynode': 0.7916823886709721, 'reg_alpha': 0.25475149740749325, 'reg_lambda': 0.3999502362723092, 'scale_pos_weight': 1.7104312787587932, 'grow_policy': 'depthwise', 'max_leaves': 162, 'max_bin': 251}. Best is trial 19 with value: 0.849599576325919.

Best trial: 19. Best value: 0.8496:  21%|██        | 21/100 [01:05<06:35,  5.00s/it]

[I 2025-11-24 22:38:30,712] Trial 20 finished with value: 0.8464323542328657 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 0.6693678580629256, 'max_delta_step': 6, 'learning_rate': 0.0021422452379732198, 'n_estimators': 1734, 'subsample': 0.6902602412406228, 'colsample_bytree': 0.6011941779190223, 'colsample_bylevel': 0.6850313325501945, 'colsample_bynode': 0.8261764495722403, 'reg_alpha': 0.19485923189516338, 'reg_lambda': 0.3305114388186892, 'scale_pos_weight': 2.9269456502040594, 'grow_policy': 'depthwise', 'max_leaves': 140, 'max_bin': 255}. Best is trial 19 with value: 0.849599576325919.

Best trial: 21. Best value: 0.850453:  22%|██▏       | 22/100 [01:09<05:55,  4.56s/it]

[I 2025-11-24 22:38:34,238] Trial 21 finished with value: 0.8504533829342014 and parameters: {'max_depth': 13, 'min_child_weight': 6, 'gamma': 2.5835124335463364, 'max_delta_step': 6, 'learning_rate': 0.0051169899136166465, 'n_estimators': 1653, 'subsample': 0.6006552432576922, 'colsample_bytree': 0.6588398716853593, 'colsample_bylevel': 0.7825330643846838, 'colsample_bynode': 0.7675917467224096, 'reg_alpha': 2.5390002461806698, 'reg_lambda': 1.9844274200448075, 'scale_pos_weight': 1.717915822572, 'grow_policy': 'depthwise', 'max_leaves': 175, 'max_bin': 247}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  23%|██▎       | 23/100 [01:15<06:15,  4.88s/it]

[I 2025-11-24 22:38:39,868] Trial 22 finished with value: 0.8482704280658244 and parameters: {'max_depth': 13, 'min_child_weight': 6, 'gamma': 2.5898006981498356, 'max_delta_step': 6, 'learning_rate': 0.0014264194222915968, 'n_estimators': 1665, 'subsample': 0.6044010771492475, 'colsample_bytree': 0.6485868229086154, 'colsample_bylevel': 0.7914845261209299, 'colsample_bynode': 0.7847033279557526, 'reg_alpha': 2.1698735206688435, 'reg_lambda': 2.7107585770515983, 'scale_pos_weight': 3.903102010350709, 'grow_policy': 'depthwise', 'max_leaves': 222, 'max_bin': 185}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  24%|██▍       | 24/100 [01:19<05:48,  4.58s/it]

[I 2025-11-24 22:38:43,755] Trial 23 finished with value: 0.8499044149939291 and parameters: {'max_depth': 13, 'min_child_weight': 7, 'gamma': 2.799288254303575, 'max_delta_step': 5, 'learning_rate': 0.004554964616663797, 'n_estimators': 1896, 'subsample': 0.7012242951010378, 'colsample_bytree': 0.7656483338514684, 'colsample_bylevel': 0.838435169912373, 'colsample_bynode': 0.766265991879626, 'reg_alpha': 4.7468375749252845, 'reg_lambda': 0.15100948829401278, 'scale_pos_weight': 1.7199826129096654, 'grow_policy': 'depthwise', 'max_leaves': 172, 'max_bin': 258}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  25%|██▌       | 25/100 [01:24<05:58,  4.78s/it]

[I 2025-11-24 22:38:48,985] Trial 24 finished with value: 0.8500090418248987 and parameters: {'max_depth': 14, 'min_child_weight': 7, 'gamma': 2.3874694044248823, 'max_delta_step': 5, 'learning_rate': 0.0026735585941390144, 'n_estimators': 1831, 'subsample': 0.6744345713409662, 'colsample_bytree': 0.7650250162454884, 'colsample_bylevel': 0.8390969451838616, 'colsample_bynode': 0.7661871632457414, 'reg_alpha': 7.224439149678992, 'reg_lambda': 0.10105486706576076, 'scale_pos_weight': 2.643006606298022, 'grow_policy': 'depthwise', 'max_leaves': 203, 'max_bin': 259}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  26%|██▌       | 26/100 [01:28<05:48,  4.72s/it]

[I 2025-11-24 22:38:53,558] Trial 25 finished with value: 0.8500594177064766 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 2.2134081454509698, 'max_delta_step': 5, 'learning_rate': 0.004433940042376348, 'n_estimators': 1799, 'subsample': 0.6560825456750305, 'colsample_bytree': 0.778662864603209, 'colsample_bylevel': 0.858324100300793, 'colsample_bynode': 0.7657842414135436, 'reg_alpha': 8.537796086836668, 'reg_lambda': 0.08712282121015419, 'scale_pos_weight': 2.7492712736442373, 'grow_policy': 'depthwise', 'max_leaves': 199, 'max_bin': 343}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  27%|██▋       | 27/100 [01:36<06:40,  5.49s/it]

[I 2025-11-24 22:39:00,844] Trial 26 finished with value: 0.8494368234777442 and parameters: {'max_depth': 15, 'min_child_weight': 10, 'gamma': 2.234010118031157, 'max_delta_step': 0, 'learning_rate': 0.002746283858729966, 'n_estimators': 1459, 'subsample': 0.6560504154529287, 'colsample_bytree': 0.8132468529651452, 'colsample_bylevel': 0.8776794289610873, 'colsample_bynode': 0.8423519645230525, 'reg_alpha': 8.415145503334559, 'reg_lambda': 0.061017138042415625, 'scale_pos_weight': 4.231193141318409, 'grow_policy': 'lossguide', 'max_leaves': 196, 'max_bin': 340}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  28%|██▊       | 28/100 [01:41<06:37,  5.51s/it]

[I 2025-11-24 22:39:06,421] Trial 27 finished with value: 0.8393267715518355 and parameters: {'max_depth': 14, 'min_child_weight': 9, 'gamma': 1.0877904885971152, 'max_delta_step': 2, 'learning_rate': 0.01402937368577679, 'n_estimators': 1848, 'subsample': 0.60349287919281, 'colsample_bytree': 0.8373345005093128, 'colsample_bylevel': 0.8229318216513729, 'colsample_bynode': 0.6757707459459525, 'reg_alpha': 9.868876959163885, 'reg_lambda': 0.027522604091878813, 'scale_pos_weight': 5.828063443647521, 'grow_policy': 'depthwise', 'max_leaves': 224, 'max_bin': 321}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  29%|██▉       | 29/100 [01:46<06:09,  5.20s/it]

[I 2025-11-24 22:39:10,905] Trial 28 finished with value: 0.8489072308765404 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 2.2935033192307284, 'max_delta_step': 3, 'learning_rate': 0.001276832199209343, 'n_estimators': 1322, 'subsample': 0.6610984642306854, 'colsample_bytree': 0.7484527424276722, 'colsample_bylevel': 0.8693745677308026, 'colsample_bynode': 0.8638343227329781, 'reg_alpha': 4.861744994545951, 'reg_lambda': 0.007977423784808636, 'scale_pos_weight': 2.709998941627378, 'grow_policy': 'depthwise', 'max_leaves': 256, 'max_bin': 362}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  30%|███       | 30/100 [01:50<05:48,  4.98s/it]

[I 2025-11-24 22:39:15,350] Trial 29 finished with value: 0.8263039603193056 and parameters: {'max_depth': 10, 'min_child_weight': 7, 'gamma': 1.2145765795526198, 'max_delta_step': 3, 'learning_rate': 0.0248119500873295, 'n_estimators': 1591, 'subsample': 0.6238204968503995, 'colsample_bytree': 0.8383047413874286, 'colsample_bylevel': 0.8105083510190109, 'colsample_bynode': 0.7607241023869665, 'reg_alpha': 1.2969175561724466, 'reg_lambda': 0.001986042269447925, 'scale_pos_weight': 3.136932493997403, 'grow_policy': 'depthwise', 'max_leaves': 203, 'max_bin': 393}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  31%|███       | 31/100 [01:51<04:17,  3.73s/it]

[I 2025-11-24 22:39:16,173] Trial 30 finished with value: 0.8494135730708621 and parameters: {'max_depth': 15, 'min_child_weight': 9, 'gamma': 2.9476369446366526, 'max_delta_step': 5, 'learning_rate': 0.00504455414227983, 'n_estimators': 226, 'subsample': 0.6707709518918586, 'colsample_bytree': 0.7893419999148723, 'colsample_bylevel': 0.9002862228032209, 'colsample_bynode': 0.8109040286557552, 'reg_alpha': 0.41427172762385783, 'reg_lambda': 0.06409610892810345, 'scale_pos_weight': 2.2905345251817955, 'grow_policy': 'depthwise', 'max_leaves': 231, 'max_bin': 305}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  32%|███▏      | 32/100 [01:55<04:17,  3.79s/it]

[I 2025-11-24 22:39:20,093] Trial 31 finished with value: 0.8493748223927251 and parameters: {'max_depth': 13, 'min_child_weight': 7, 'gamma': 2.8919383527554725, 'max_delta_step': 5, 'learning_rate': 0.004479493420740475, 'n_estimators': 1861, 'subsample': 0.7250217682498417, 'colsample_bytree': 0.7641194792631019, 'colsample_bylevel': 0.8346175004423937, 'colsample_bynode': 0.7633980320521091, 'reg_alpha': 3.4516001746573557, 'reg_lambda': 0.1430704808729159, 'scale_pos_weight': 1.6793512796877508, 'grow_policy': 'depthwise', 'max_leaves': 201, 'max_bin': 275}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  33%|███▎      | 33/100 [02:00<04:37,  4.14s/it]

[I 2025-11-24 22:39:25,043] Trial 32 finished with value: 0.8501640445374461 and parameters: {'max_depth': 11, 'min_child_weight': 7, 'gamma': 2.398446840020317, 'max_delta_step': 4, 'learning_rate': 0.0026733336446700734, 'n_estimators': 1723, 'subsample': 0.6824786384680726, 'colsample_bytree': 0.7339347222488315, 'colsample_bylevel': 0.8507448010977648, 'colsample_bynode': 0.7413592770841948, 'reg_alpha': 5.631763001513329, 'reg_lambda': 0.1474430467884188, 'scale_pos_weight': 2.0804389076314647, 'grow_policy': 'depthwise', 'max_leaves': 175, 'max_bin': 315}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  34%|███▍      | 34/100 [02:05<04:51,  4.42s/it]

[I 2025-11-24 22:39:30,134] Trial 33 finished with value: 0.8479100467591516 and parameters: {'max_depth': 9, 'min_child_weight': 9, 'gamma': 2.3457040737848693, 'max_delta_step': 4, 'learning_rate': 0.0025068823886226364, 'n_estimators': 1723, 'subsample': 0.6303816762393174, 'colsample_bytree': 0.7207896859108964, 'colsample_bylevel': 0.8690045375874098, 'colsample_bynode': 0.6528143967838582, 'reg_alpha': 1.8370056548677638, 'reg_lambda': 0.016997570846975108, 'scale_pos_weight': 3.406722963810876, 'grow_policy': 'depthwise', 'max_leaves': 145, 'max_bin': 331}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  35%|███▌      | 35/100 [02:10<05:09,  4.76s/it]

[I 2025-11-24 22:39:35,685] Trial 34 finished with value: 0.849299904414994 and parameters: {'max_depth': 11, 'min_child_weight': 8, 'gamma': 1.965922292991142, 'max_delta_step': 4, 'learning_rate': 0.0017055664746421437, 'n_estimators': 1760, 'subsample': 0.6820440698260903, 'colsample_bytree': 0.6959441293865494, 'colsample_bylevel': 0.8037267432144165, 'colsample_bynode': 0.7320803123713554, 'reg_alpha': 5.463520199233876, 'reg_lambda': 0.04395653169030081, 'scale_pos_weight': 2.4745929486706615, 'grow_policy': 'depthwise', 'max_leaves': 213, 'max_bin': 373}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  36%|███▌      | 36/100 [02:12<04:01,  3.77s/it]

[I 2025-11-24 22:39:37,157] Trial 35 finished with value: 0.8350564468211527 and parameters: {'max_depth': 11, 'min_child_weight': 7, 'gamma': 2.500939036129504, 'max_delta_step': 6, 'learning_rate': 0.26440402348574227, 'n_estimators': 1487, 'subsample': 0.7743731795436899, 'colsample_bytree': 0.7396725177447991, 'colsample_bylevel': 0.889997036580447, 'colsample_bynode': 0.6989295237883965, 'reg_alpha': 9.485767733417527, 'reg_lambda': 0.20454923928043472, 'scale_pos_weight': 4.015378338573459, 'grow_policy': 'depthwise', 'max_leaves': 249, 'max_bin': 306}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  37%|███▋      | 37/100 [02:19<04:53,  4.65s/it]

[I 2025-11-24 22:39:43,859] Trial 36 finished with value: 0.8448332429150843 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 2.0557538081367883, 'max_delta_step': 3, 'learning_rate': 0.0032215328323106558, 'n_estimators': 1828, 'subsample': 0.6446691497894859, 'colsample_bytree': 0.9393512454015047, 'colsample_bylevel': 0.9147875463389608, 'colsample_bynode': 0.6198576832628551, 'reg_alpha': 1.306697130917009, 'reg_lambda': 0.5660202646423423, 'scale_pos_weight': 3.003902585564346, 'grow_policy': 'depthwise', 'max_leaves': 186, 'max_bin': 437}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  38%|███▊      | 38/100 [02:22<04:24,  4.27s/it]

[I 2025-11-24 22:39:47,242] Trial 37 finished with value: 0.844205481929267 and parameters: {'max_depth': 10, 'min_child_weight': 5, 'gamma': 3.089798876174556, 'max_delta_step': 4, 'learning_rate': 0.00591607496316516, 'n_estimators': 1649, 'subsample': 0.725610324117647, 'colsample_bytree': 0.8110451432579842, 'colsample_bylevel': 0.9251575412665861, 'colsample_bynode': 0.8966968149168395, 'reg_alpha': 0.02459362774821777, 'reg_lambda': 0.10099166066057914, 'scale_pos_weight': 2.3102011933441613, 'grow_policy': 'depthwise', 'max_leaves': 84, 'max_bin': 279}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  39%|███▉      | 39/100 [02:26<04:07,  4.06s/it]

[I 2025-11-24 22:39:50,791] Trial 38 finished with value: 0.8342491410266346 and parameters: {'max_depth': 12, 'min_child_weight': 6, 'gamma': 1.3715338679828935, 'max_delta_step': 8, 'learning_rate': 0.019115205271351327, 'n_estimators': 1146, 'subsample': 0.6015029514902966, 'colsample_bytree': 0.773897489253131, 'colsample_bylevel': 0.7813291940542312, 'colsample_bynode': 0.8588664753950872, 'reg_alpha': 3.7757057282312125, 'reg_lambda': 0.016137586788544888, 'scale_pos_weight': 3.4641475607514, 'grow_policy': 'depthwise', 'max_leaves': 114, 'max_bin': 243}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  40%|████      | 40/100 [02:32<04:41,  4.69s/it]

[I 2025-11-24 22:39:56,953] Trial 39 finished with value: 0.8353160763646696 and parameters: {'max_depth': 14, 'min_child_weight': 9, 'gamma': 0.9963717585823706, 'max_delta_step': 6, 'learning_rate': 0.008874501095237804, 'n_estimators': 1538, 'subsample': 0.6726630087329305, 'colsample_bytree': 0.7286832237052533, 'colsample_bylevel': 0.9974400378933901, 'colsample_bynode': 0.7787026646859873, 'reg_alpha': 1.5106105261500913, 'reg_lambda': 1.911336367259049, 'scale_pos_weight': 4.329615360431169, 'grow_policy': 'depthwise', 'max_leaves': 157, 'max_bin': 320}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 21. Best value: 0.850453:  41%|████      | 41/100 [02:47<07:51,  7.99s/it]

[I 2025-11-24 22:40:12,663] Trial 40 finished with value: 0.8477214601255522 and parameters: {'max_depth': 13, 'min_child_weight': 5, 'gamma': 1.814209884368924, 'max_delta_step': 5, 'learning_rate': 0.00306564845913822, 'n_estimators': 1792, 'subsample': 0.6270016909690779, 'colsample_bytree': 0.6739475302864142, 'colsample_bylevel': 0.8577429061172713, 'colsample_bynode': 0.813391092543184, 'reg_alpha': 0.00105309909739184, 'reg_lambda': 3.935958941354515, 'scale_pos_weight': 2.0361909583919164, 'grow_policy': 'lossguide', 'max_leaves': 136, 'max_bin': 292}. Best is trial 21 with value: 0.8504533829342014.

Best trial: 41. Best value: 0.850796:  42%|████▏     | 42/100 [02:51<06:30,  6.73s/it]

[I 2025-11-24 22:40:16,432] Trial 41 finished with value: 0.8507956805910769 and parameters: {'max_depth': 13, 'min_child_weight': 7, 'gamma': 2.7236606698207977, 'max_delta_step': 5, 'learning_rate': 0.004929565149187465, 'n_estimators': 1905, 'subsample': 0.7078091962679229, 'colsample_bytree': 0.7688314574755084, 'colsample_bylevel': 0.8373959269801451, 'colsample_bynode': 0.7668442747135187, 'reg_alpha': 5.09730171117216, 'reg_lambda': 0.15685360210661248, 'scale_pos_weight': 1.4592430414207196, 'grow_policy': 'depthwise', 'max_leaves': 171, 'max_bin': 239}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  43%|████▎     | 43/100 [02:57<05:59,  6.31s/it]

[I 2025-11-24 22:40:21,773] Trial 42 finished with value: 0.8500865431811723 and parameters: {'max_depth': 15, 'min_child_weight': 7, 'gamma': 2.212301926539116, 'max_delta_step': 4, 'learning_rate': 0.0019471237494863704, 'n_estimators': 1904, 'subsample': 0.7207211031988036, 'colsample_bytree': 0.7966464612645867, 'colsample_bylevel': 0.8201365555467837, 'colsample_bynode': 0.7436056442238186, 'reg_alpha': 5.6708952903310355, 'reg_lambda': 0.10840954859571304, 'scale_pos_weight': 1.5117925348605665, 'grow_policy': 'depthwise', 'max_leaves': 122, 'max_bin': 235}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  44%|████▍     | 44/100 [03:03<05:56,  6.37s/it]

[I 2025-11-24 22:40:28,272] Trial 43 finished with value: 0.8488943139838281 and parameters: {'max_depth': 15, 'min_child_weight': 6, 'gamma': 1.6613613144354296, 'max_delta_step': 2, 'learning_rate': 0.0019757572151749892, 'n_estimators': 1937, 'subsample': 0.7103955144644211, 'colsample_bytree': 0.8025417585553624, 'colsample_bylevel': 0.818621470880192, 'colsample_bynode': 0.7430253376761409, 'reg_alpha': 2.9739162355779234, 'reg_lambda': 0.04558454977556016, 'scale_pos_weight': 1.3742444124617053, 'grow_policy': 'depthwise', 'max_leaves': 66, 'max_bin': 168}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  45%|████▌     | 45/100 [03:07<05:14,  5.71s/it]

[I 2025-11-24 22:40:32,462] Trial 44 finished with value: 0.8479810896690693 and parameters: {'max_depth': 15, 'min_child_weight': 8, 'gamma': 3.6851884997191275, 'max_delta_step': 4, 'learning_rate': 0.0010226368465380586, 'n_estimators': 1692, 'subsample': 0.6434771079466661, 'colsample_bytree': 0.8519545430687028, 'colsample_bylevel': 0.8576834625493039, 'colsample_bynode': 0.6949670278301924, 'reg_alpha': 5.729806716861519, 'reg_lambda': 0.21750929605552805, 'scale_pos_weight': 1.0140109857122714, 'grow_policy': 'depthwise', 'max_leaves': 118, 'max_bin': 378}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  46%|████▌     | 46/100 [03:12<04:55,  5.47s/it]

[I 2025-11-24 22:40:37,379] Trial 45 finished with value: 0.8476387920121935 and parameters: {'max_depth': 12, 'min_child_weight': 7, 'gamma': 2.6492755672470123, 'max_delta_step': 3, 'learning_rate': 0.0037230084372682796, 'n_estimators': 1905, 'subsample': 0.7429455019223715, 'colsample_bytree': 0.9074607967184761, 'colsample_bylevel': 0.7154165705944391, 'colsample_bynode': 0.7291829323106972, 'reg_alpha': 0.4664714700436633, 'reg_lambda': 0.5665595040557956, 'scale_pos_weight': 2.028610831678651, 'grow_policy': 'depthwise', 'max_leaves': 129, 'max_bin': 236}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  47%|████▋     | 47/100 [03:14<03:46,  4.27s/it]

[I 2025-11-24 22:40:38,834] Trial 46 finished with value: 0.8501769614301583 and parameters: {'max_depth': 7, 'min_child_weight': 8, 'gamma': 2.207102216314902, 'max_delta_step': 4, 'learning_rate': 0.007061202544275182, 'n_estimators': 540, 'subsample': 0.7850708055221519, 'colsample_bytree': 0.7912663311260355, 'colsample_bylevel': 0.7990236969879673, 'colsample_bynode': 0.9391249736396152, 'reg_alpha': 4.5160576845998985, 'reg_lambda': 0.003812237721730779, 'scale_pos_weight': 1.4438422996242366, 'grow_policy': 'depthwise', 'max_leaves': 170, 'max_bin': 280}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  48%|████▊     | 48/100 [03:15<02:55,  3.38s/it]

[I 2025-11-24 22:40:40,154] Trial 47 finished with value: 0.8489627735152031 and parameters: {'max_depth': 5, 'min_child_weight': 4, 'gamma': 3.291479283880061, 'max_delta_step': 3, 'learning_rate': 0.006954927948562472, 'n_estimators': 724, 'subsample': 0.7994942367331065, 'colsample_bytree': 0.629883607227993, 'colsample_bylevel': 0.7967471539518229, 'colsample_bynode': 0.9195667071992115, 'reg_alpha': 1.8130782545390172, 'reg_lambda': 0.0031773233212193793, 'scale_pos_weight': 1.4748970576673255, 'grow_policy': 'depthwise', 'max_leaves': 165, 'max_bin': 278}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  49%|████▉     | 49/100 [03:20<03:19,  3.92s/it]

[I 2025-11-24 22:40:45,326] Trial 48 finished with value: 0.8420561109819422 and parameters: {'max_depth': 7, 'min_child_weight': 5, 'gamma': 1.984239411383328, 'max_delta_step': 4, 'learning_rate': 0.010837302763264828, 'n_estimators': 505, 'subsample': 0.7843516287583255, 'colsample_bytree': 0.8255051730519999, 'colsample_bylevel': 0.7697896206999468, 'colsample_bynode': 0.9580524491223996, 'reg_alpha': 0.0036478042987681362, 'reg_lambda': 0.04307774623977451, 'scale_pos_weight': 8.101248320362737, 'grow_policy': 'lossguide', 'max_leaves': 100, 'max_bin': 509}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  50%|█████     | 50/100 [03:22<02:40,  3.22s/it]

[I 2025-11-24 22:40:46,904] Trial 49 finished with value: 0.8489756904079155 and parameters: {'max_depth': 7, 'min_child_weight': 6, 'gamma': 3.0694526680150007, 'max_delta_step': 2, 'learning_rate': 0.013538380376996912, 'n_estimators': 935, 'subsample': 0.7548736424070213, 'colsample_bytree': 0.8569648634578023, 'colsample_bylevel': 0.8244759044482108, 'colsample_bynode': 0.8289664242723248, 'reg_alpha': 0.9688175032320835, 'reg_lambda': 0.009849596346684952, 'scale_pos_weight': 1.261179422929055, 'grow_policy': 'depthwise', 'max_leaves': 175, 'max_bin': 193}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  51%|█████     | 51/100 [03:22<02:01,  2.48s/it]

[I 2025-11-24 22:40:47,678] Trial 50 finished with value: 0.8479475057480174 and parameters: {'max_depth': 6, 'min_child_weight': 7, 'gamma': 1.535613167134306, 'max_delta_step': 1, 'learning_rate': 0.005484824370579427, 'n_estimators': 319, 'subsample': 0.7199762654882642, 'colsample_bytree': 0.6998639784907847, 'colsample_bylevel': 0.7854418895513098, 'colsample_bynode': 0.9262399251821511, 'reg_alpha': 0.11322086454849792, 'reg_lambda': 0.0037227130971664575, 'scale_pos_weight': 2.0029548893597813, 'grow_policy': 'depthwise', 'max_leaves': 188, 'max_bin': 208}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  52%|█████▏    | 52/100 [03:27<02:28,  3.10s/it]

[I 2025-11-24 22:40:52,219] Trial 51 finished with value: 0.8505489679402722 and parameters: {'max_depth': 8, 'min_child_weight': 8, 'gamma': 2.166756228856085, 'max_delta_step': 5, 'learning_rate': 0.003525192117582512, 'n_estimators': 1975, 'subsample': 0.6921866916956276, 'colsample_bytree': 0.7868436064915045, 'colsample_bylevel': 0.8535201946688652, 'colsample_bynode': 0.7982951899312707, 'reg_alpha': 4.521993591541097, 'reg_lambda': 0.16316133939321062, 'scale_pos_weight': 1.4661725927888916, 'grow_policy': 'depthwise', 'max_leaves': 153, 'max_bin': 235}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  53%|█████▎    | 53/100 [03:32<02:59,  3.82s/it]

[I 2025-11-24 22:40:57,724] Trial 52 finished with value: 0.8433968844454778 and parameters: {'max_depth': 8, 'min_child_weight': 9, 'gamma': 1.8101158559771608, 'max_delta_step': 4, 'learning_rate': 0.0034029548079537366, 'n_estimators': 1996, 'subsample': 0.6911013752873196, 'colsample_bytree': 0.796937222268501, 'colsample_bylevel': 0.8830713430003274, 'colsample_bynode': 0.7950955293659424, 'reg_alpha': 4.1730026419428325, 'reg_lambda': 0.196687777220629, 'scale_pos_weight': 9.776171154319073, 'grow_policy': 'depthwise', 'max_leaves': 123, 'max_bin': 229}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  54%|█████▍    | 54/100 [03:36<02:46,  3.62s/it]

[I 2025-11-24 22:41:00,876] Trial 53 finished with value: 0.8477007930972125 and parameters: {'max_depth': 9, 'min_child_weight': 8, 'gamma': 2.152087963081163, 'max_delta_step': 6, 'learning_rate': 0.007246639916944573, 'n_estimators': 1939, 'subsample': 0.8248754403809453, 'colsample_bytree': 0.7483794768218006, 'colsample_bylevel': 0.8079987572659486, 'colsample_bynode': 0.7474273806918716, 'reg_alpha': 2.8382480585736056, 'reg_lambda': 0.1279102871537582, 'scale_pos_weight': 1.4181363256588904, 'grow_policy': 'depthwise', 'max_leaves': 151, 'max_bin': 237}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  55%|█████▌    | 55/100 [03:37<02:16,  3.04s/it]

[I 2025-11-24 22:41:02,568] Trial 54 finished with value: 0.8485326409878841 and parameters: {'max_depth': 7, 'min_child_weight': 7, 'gamma': 2.671362179019338, 'max_delta_step': 5, 'learning_rate': 0.00200951935123831, 'n_estimators': 682, 'subsample': 0.728325247166427, 'colsample_bytree': 0.8207419868402883, 'colsample_bylevel': 0.8458584990573739, 'colsample_bynode': 0.7126308803364537, 'reg_alpha': 5.85827776600318, 'reg_lambda': 0.24999106761853518, 'scale_pos_weight': 1.8168029189057708, 'grow_policy': 'depthwise', 'max_leaves': 162, 'max_bin': 271}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  56%|█████▌    | 56/100 [03:40<02:13,  3.03s/it]

[I 2025-11-24 22:41:05,567] Trial 55 finished with value: 0.8489976491255264 and parameters: {'max_depth': 6, 'min_child_weight': 6, 'gamma': 2.43680493180618, 'max_delta_step': 4, 'learning_rate': 0.001585907172348579, 'n_estimators': 1354, 'subsample': 0.7529722740853447, 'colsample_bytree': 0.7855395496618247, 'colsample_bylevel': 0.753280954078307, 'colsample_bynode': 0.7781699144094518, 'reg_alpha': 2.308469033348051, 'reg_lambda': 0.4667148696874235, 'scale_pos_weight': 1.000452836201648, 'grow_policy': 'depthwise', 'max_leaves': 137, 'max_bin': 175}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  57%|█████▋    | 57/100 [03:42<01:54,  2.65s/it]

[I 2025-11-24 22:41:07,341] Trial 56 finished with value: 0.8466080239737528 and parameters: {'max_depth': 8, 'min_child_weight': 8, 'gamma': 2.76095308082646, 'max_delta_step': 6, 'learning_rate': 0.03479726505959828, 'n_estimators': 1611, 'subsample': 0.7665317706968429, 'colsample_bytree': 0.7337366087211755, 'colsample_bylevel': 0.8261029496458581, 'colsample_bynode': 0.8722953043935187, 'reg_alpha': 0.5177477342891809, 'reg_lambda': 6.6332082115304365, 'scale_pos_weight': 2.098557172902983, 'grow_policy': 'depthwise', 'max_leaves': 174, 'max_bin': 143}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  58%|█████▊    | 58/100 [03:50<02:51,  4.08s/it]

[I 2025-11-24 22:41:14,734] Trial 57 finished with value: 0.8489369397297786 and parameters: {'max_depth': 9, 'min_child_weight': 6, 'gamma': 3.467889604447293, 'max_delta_step': 8, 'learning_rate': 0.0023219493287609506, 'n_estimators': 988, 'subsample': 0.7898751610351067, 'colsample_bytree': 0.7120092548219977, 'colsample_bylevel': 0.7688611817355382, 'colsample_bynode': 0.7983569917881922, 'reg_alpha': 1.0939114776803673, 'reg_lambda': 0.01885565606270452, 'scale_pos_weight': 1.569486699114059, 'grow_policy': 'lossguide', 'max_leaves': 147, 'max_bin': 203}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  59%|█████▉    | 59/100 [03:54<02:47,  4.09s/it]

[I 2025-11-24 22:41:18,869] Trial 58 finished with value: 0.8443217339636777 and parameters: {'max_depth': 8, 'min_child_weight': 7, 'gamma': 1.8061318892183333, 'max_delta_step': 5, 'learning_rate': 0.008386893824210085, 'n_estimators': 1894, 'subsample': 0.7034971799025288, 'colsample_bytree': 0.7576184205041414, 'colsample_bylevel': 0.7984696186543161, 'colsample_bynode': 0.8271002125993906, 'reg_alpha': 4.280658173770964, 'reg_lambda': 0.0010955214713725151, 'scale_pos_weight': 2.4179538596346912, 'grow_policy': 'depthwise', 'max_leaves': 190, 'max_bin': 216}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  60%|██████    | 60/100 [03:58<02:43,  4.10s/it]

[I 2025-11-24 22:41:22,971] Trial 59 finished with value: 0.8464052287581698 and parameters: {'max_depth': 6, 'min_child_weight': 10, 'gamma': 2.135024870783199, 'max_delta_step': 4, 'learning_rate': 0.005337183514318866, 'n_estimators': 2000, 'subsample': 0.8116812984476927, 'colsample_bytree': 0.7993263108128548, 'colsample_bylevel': 0.7271991049327349, 'colsample_bynode': 0.7240761427007463, 'reg_alpha': 6.290527492582845, 'reg_lambda': 1.5665821617003235, 'scale_pos_weight': 7.0967405599350215, 'grow_policy': 'depthwise', 'max_leaves': 158, 'max_bin': 247}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  61%|██████    | 61/100 [04:03<02:48,  4.32s/it]

[I 2025-11-24 22:41:27,804] Trial 60 finished with value: 0.8486928104575163 and parameters: {'max_depth': 10, 'min_child_weight': 8, 'gamma': 2.476420799623042, 'max_delta_step': 6, 'learning_rate': 0.0012622731345862679, 'n_estimators': 1750, 'subsample': 0.6899385649537549, 'colsample_bytree': 0.6370639298232597, 'colsample_bylevel': 0.9547391023244575, 'colsample_bynode': 0.6815291625212732, 'reg_alpha': 3.15293503621436, 'reg_lambda': 3.811690411224217, 'scale_pos_weight': 1.527872257818975, 'grow_policy': 'depthwise', 'max_leaves': 109, 'max_bin': 284}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  62%|██████▏   | 62/100 [04:07<02:50,  4.49s/it]

[I 2025-11-24 22:41:32,682] Trial 61 finished with value: 0.8498204551912992 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 2.2184684367485006, 'max_delta_step': 5, 'learning_rate': 0.004057612332340147, 'n_estimators': 1814, 'subsample': 0.6594109221262479, 'colsample_bytree': 0.7783361103782092, 'colsample_bylevel': 0.8535792673917829, 'colsample_bynode': 0.7516234372047832, 'reg_alpha': 7.510763971163205, 'reg_lambda': 0.0758411694331957, 'scale_pos_weight': 2.6455296493658134, 'grow_policy': 'depthwise', 'max_leaves': 177, 'max_bin': 302}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  63%|██████▎   | 63/100 [04:12<02:44,  4.43s/it]

[I 2025-11-24 22:41:36,999] Trial 62 finished with value: 0.8504443411093028 and parameters: {'max_depth': 13, 'min_child_weight': 7, 'gamma': 2.9558319813544145, 'max_delta_step': 5, 'learning_rate': 0.0043981515044609005, 'n_estimators': 1881, 'subsample': 0.7143944960359381, 'colsample_bytree': 0.7783975936990772, 'colsample_bylevel': 0.8702712594951798, 'colsample_bynode': 0.7726189412313214, 'reg_alpha': 9.721961357678063, 'reg_lambda': 0.0900080420262289, 'scale_pos_weight': 2.8505132219738334, 'grow_policy': 'depthwise', 'max_leaves': 211, 'max_bin': 341}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  64%|██████▍   | 64/100 [04:16<02:34,  4.29s/it]

[I 2025-11-24 22:41:40,954] Trial 63 finished with value: 0.8498553308016223 and parameters: {'max_depth': 12, 'min_child_weight': 7, 'gamma': 2.916636442351949, 'max_delta_step': 5, 'learning_rate': 0.0031361326913546816, 'n_estimators': 1885, 'subsample': 0.7342704871302165, 'colsample_bytree': 0.8147100052009717, 'colsample_bylevel': 0.8677338716633851, 'colsample_bynode': 0.7774574701774297, 'reg_alpha': 4.856572089799366, 'reg_lambda': 9.780836240946622, 'scale_pos_weight': 1.3231319233995018, 'grow_policy': 'depthwise', 'max_leaves': 214, 'max_bin': 312}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  65%|██████▌   | 65/100 [04:19<02:24,  4.13s/it]

[I 2025-11-24 22:41:44,721] Trial 64 finished with value: 0.8479022966235242 and parameters: {'max_depth': 13, 'min_child_weight': 7, 'gamma': 2.575650407122142, 'max_delta_step': 4, 'learning_rate': 0.0065205435930816074, 'n_estimators': 1942, 'subsample': 0.7140045880957174, 'colsample_bytree': 0.7896961630488695, 'colsample_bylevel': 0.8354278885605664, 'colsample_bynode': 0.7385949030681022, 'reg_alpha': 2.1293450603301025, 'reg_lambda': 0.6998161949991836, 'scale_pos_weight': 1.753484703227015, 'grow_policy': 'depthwise', 'max_leaves': 169, 'max_bin': 262}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  66%|██████▌   | 66/100 [04:24<02:21,  4.15s/it]

[I 2025-11-24 22:41:48,911] Trial 65 finished with value: 0.8497545790384664 and parameters: {'max_depth': 12, 'min_child_weight': 6, 'gamma': 3.2062245673112635, 'max_delta_step': 5, 'learning_rate': 0.002704543226055637, 'n_estimators': 1689, 'subsample': 0.8411220126911607, 'colsample_bytree': 0.6735398433813213, 'colsample_bylevel': 0.9019084836770562, 'colsample_bynode': 0.7085914792573343, 'reg_alpha': 9.85542030721073, 'reg_lambda': 0.033885917935835855, 'scale_pos_weight': 2.273082022960554, 'grow_policy': 'depthwise', 'max_leaves': 182, 'max_bin': 331}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  67%|██████▋   | 67/100 [04:29<02:26,  4.45s/it]

[I 2025-11-24 22:41:54,069] Trial 66 finished with value: 0.8452091244930119 and parameters: {'max_depth': 12, 'min_child_weight': 7, 'gamma': 2.35827060993537, 'max_delta_step': 6, 'learning_rate': 0.0048184537917570856, 'n_estimators': 1541, 'subsample': 0.6964827206950365, 'colsample_bytree': 0.7715277010059091, 'colsample_bylevel': 0.8461176828334559, 'colsample_bynode': 0.8059118572192805, 'reg_alpha': 6.756253459286796, 'reg_lambda': 0.30653715463557035, 'scale_pos_weight': 5.554678406990789, 'grow_policy': 'depthwise', 'max_leaves': 194, 'max_bin': 291}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  68%|██████▊   | 68/100 [04:41<03:35,  6.72s/it]

[I 2025-11-24 22:42:06,085] Trial 67 finished with value: 0.8479604226407296 and parameters: {'max_depth': 11, 'min_child_weight': 9, 'gamma': 2.9859030501668986, 'max_delta_step': 7, 'learning_rate': 0.0036449793001221585, 'n_estimators': 1772, 'subsample': 0.7442703079841174, 'colsample_bytree': 0.837577332636466, 'colsample_bylevel': 0.878067944288327, 'colsample_bynode': 0.7575397792653249, 'reg_alpha': 3.8537238350746845, 'reg_lambda': 0.16385381547599662, 'scale_pos_weight': 2.8467956189133967, 'grow_policy': 'lossguide', 'max_leaves': 138, 'max_bin': 356}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  69%|██████▉   | 69/100 [04:46<03:16,  6.34s/it]

[I 2025-11-24 22:42:11,541] Trial 68 finished with value: 0.8491578185951587 and parameters: {'max_depth': 13, 'min_child_weight': 6, 'gamma': 3.3029288998325566, 'max_delta_step': 3, 'learning_rate': 0.0017857431099948305, 'n_estimators': 1856, 'subsample': 0.6189103298902454, 'colsample_bytree': 0.7550951207205739, 'colsample_bylevel': 0.8141452755815973, 'colsample_bynode': 0.784367974200409, 'reg_alpha': 0.02987339146742348, 'reg_lambda': 0.12603706083358693, 'scale_pos_weight': 1.8187473761072055, 'grow_policy': 'depthwise', 'max_leaves': 124, 'max_bin': 224}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  70%|███████   | 70/100 [04:48<02:27,  4.93s/it]

[I 2025-11-24 22:42:13,177] Trial 69 finished with value: 0.8419863597612959 and parameters: {'max_depth': 9, 'min_child_weight': 5, 'gamma': 2.7455836557014237, 'max_delta_step': 4, 'learning_rate': 0.07314307343159444, 'n_estimators': 1726, 'subsample': 0.6816983672055151, 'colsample_bytree': 0.7425355266909196, 'colsample_bylevel': 0.9148300807023007, 'colsample_bynode': 0.9987937931337189, 'reg_alpha': 1.58011484253307, 'reg_lambda': 0.010148239613176336, 'scale_pos_weight': 1.2356122833452925, 'grow_policy': 'depthwise', 'max_leaves': 208, 'max_bin': 252}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  71%|███████   | 71/100 [04:49<01:50,  3.81s/it]

[I 2025-11-24 22:42:14,379] Trial 70 finished with value: 0.8469270712237464 and parameters: {'max_depth': 11, 'min_child_weight': 8, 'gamma': 3.819593492548269, 'max_delta_step': 3, 'learning_rate': 0.009771497266329185, 'n_estimators': 400, 'subsample': 0.7610639035475979, 'colsample_bytree': 0.7139090076641416, 'colsample_bylevel': 0.6069855662957762, 'colsample_bynode': 0.7925948370076613, 'reg_alpha': 0.6989974517657007, 'reg_lambda': 0.06027006883262157, 'scale_pos_weight': 3.089808115769821, 'grow_policy': 'depthwise', 'max_leaves': 90, 'max_bin': 266}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  72%|███████▏  | 72/100 [04:54<01:54,  4.10s/it]

[I 2025-11-24 22:42:19,156] Trial 71 finished with value: 0.8499638327004058 and parameters: {'max_depth': 14, 'min_child_weight': 8, 'gamma': 2.2712475666822507, 'max_delta_step': 5, 'learning_rate': 0.0042597487501675555, 'n_estimators': 1928, 'subsample': 0.6421494137254892, 'colsample_bytree': 0.779813028560169, 'colsample_bylevel': 0.8628482821889251, 'colsample_bynode': 0.7699854470459216, 'reg_alpha': 8.346636924692579, 'reg_lambda': 0.09723102198948633, 'scale_pos_weight': 2.5393692965152166, 'grow_policy': 'depthwise', 'max_leaves': 226, 'max_bin': 334}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  73%|███████▎  | 73/100 [05:00<02:02,  4.55s/it]

[I 2025-11-24 22:42:24,744] Trial 72 finished with value: 0.8494781575344235 and parameters: {'max_depth': 15, 'min_child_weight': 7, 'gamma': 2.134885359779404, 'max_delta_step': 5, 'learning_rate': 0.002718631699912725, 'n_estimators': 1803, 'subsample': 0.6657908992368724, 'colsample_bytree': 0.8068020667665883, 'colsample_bylevel': 0.8499004619431086, 'colsample_bynode': 0.7714111174963018, 'reg_alpha': 5.31082511366406, 'reg_lambda': 0.3910866276251404, 'scale_pos_weight': 2.224621804824647, 'grow_policy': 'depthwise', 'max_leaves': 197, 'max_bin': 349}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  74%|███████▍  | 74/100 [05:04<02:01,  4.66s/it]

[I 2025-11-24 22:42:29,683] Trial 73 finished with value: 0.847969464465628 and parameters: {'max_depth': 13, 'min_child_weight': 8, 'gamma': 1.9221999471233455, 'max_delta_step': 4, 'learning_rate': 0.004796667550049436, 'n_estimators': 1616, 'subsample': 0.6782041118194571, 'colsample_bytree': 0.7925591258474506, 'colsample_bylevel': 0.8241466480324974, 'colsample_bynode': 0.8188229497928942, 'reg_alpha': 7.136864941558315, 'reg_lambda': 0.08766009732827676, 'scale_pos_weight': 3.360875436292216, 'grow_policy': 'depthwise', 'max_leaves': 166, 'max_bin': 343}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  75%|███████▌  | 75/100 [05:08<01:49,  4.36s/it]

[I 2025-11-24 22:42:33,345] Trial 74 finished with value: 0.8479216719625927 and parameters: {'max_depth': 14, 'min_child_weight': 7, 'gamma': 2.8351343193657748, 'max_delta_step': 6, 'learning_rate': 0.007639561832760916, 'n_estimators': 1852, 'subsample': 0.6148220036425577, 'colsample_bytree': 0.7695994519370178, 'colsample_bylevel': 0.8910388361525695, 'colsample_bynode': 0.8376282089820407, 'reg_alpha': 2.9170832123251706, 'reg_lambda': 0.16630617626178845, 'scale_pos_weight': 1.85755398339367, 'grow_policy': 'depthwise', 'max_leaves': 186, 'max_bin': 420}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  76%|███████▌  | 76/100 [05:13<01:49,  4.57s/it]

[I 2025-11-24 22:42:38,400] Trial 75 finished with value: 0.847894546487897 and parameters: {'max_depth': 15, 'min_child_weight': 9, 'gamma': 2.4784697085254153, 'max_delta_step': 5, 'learning_rate': 0.0038796833573995215, 'n_estimators': 1701, 'subsample': 0.6478008018848512, 'colsample_bytree': 0.7581437533982692, 'colsample_bylevel': 0.8365528221929548, 'colsample_bynode': 0.7533657142519616, 'reg_alpha': 4.046079780518985, 'reg_lambda': 0.2713225226355999, 'scale_pos_weight': 2.8442241671970727, 'grow_policy': 'depthwise', 'max_leaves': 237, 'max_bin': 373}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  77%|███████▋  | 77/100 [05:17<01:38,  4.28s/it]

[I 2025-11-24 22:42:41,987] Trial 76 finished with value: 0.8504042987418947 and parameters: {'max_depth': 13, 'min_child_weight': 8, 'gamma': 0.0569095536997235, 'max_delta_step': 6, 'learning_rate': 0.006014553027134552, 'n_estimators': 1176, 'subsample': 0.7080032856790732, 'colsample_bytree': 0.7260625186968741, 'colsample_bylevel': 0.7932647559201228, 'colsample_bynode': 0.7333164719068387, 'reg_alpha': 8.90509520293412, 'reg_lambda': 0.11617596038105085, 'scale_pos_weight': 1.5912724661925097, 'grow_policy': 'depthwise', 'max_leaves': 152, 'max_bin': 315}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  78%|███████▊  | 78/100 [05:20<01:26,  3.94s/it]

[I 2025-11-24 22:42:45,127] Trial 77 finished with value: 0.850180836497972 and parameters: {'max_depth': 11, 'min_child_weight': 7, 'gamma': 0.037366885496079104, 'max_delta_step': 7, 'learning_rate': 0.0063342079006164075, 'n_estimators': 1003, 'subsample': 0.7339321905024142, 'colsample_bytree': 0.725008894559902, 'colsample_bylevel': 0.7860092914329072, 'colsample_bynode': 0.7423985425126419, 'reg_alpha': 9.796811465072377, 'reg_lambda': 0.11484401465361155, 'scale_pos_weight': 1.5755458848197128, 'grow_policy': 'depthwise', 'max_leaves': 144, 'max_bin': 468}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 41. Best value: 0.850796:  79%|███████▉  | 79/100 [05:22<01:13,  3.48s/it]

[I 2025-11-24 22:42:47,552] Trial 78 finished with value: 0.8505515513188147 and parameters: {'max_depth': 11, 'min_child_weight': 8, 'gamma': 0.0236514094665555, 'max_delta_step': 7, 'learning_rate': 0.006426547078575484, 'n_estimators': 806, 'subsample': 0.712085244645783, 'colsample_bytree': 0.7278921586792176, 'colsample_bylevel': 0.787170509650781, 'colsample_bynode': 0.717270727751754, 'reg_alpha': 8.37878590321482, 'reg_lambda': 0.05100816541871891, 'scale_pos_weight': 1.1812434169917867, 'grow_policy': 'depthwise', 'max_leaves': 145, 'max_bin': 440}. Best is trial 41 with value: 0.8507956805910769.

Best trial: 79. Best value: 0.850872:  80%|████████  | 80/100 [05:26<01:08,  3.41s/it]

[I 2025-11-24 22:42:50,797] Trial 79 finished with value: 0.8508718902580795 and parameters: {'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.052393073810884254, 'max_delta_step': 7, 'learning_rate': 0.006065985845249366, 'n_estimators': 1169, 'subsample': 0.7084499495463198, 'colsample_bytree': 0.6771159029961427, 'colsample_bylevel': 0.7475908968429646, 'colsample_bynode': 0.7192972947521565, 'reg_alpha': 9.101413723284493, 'reg_lambda': 0.04947789855089188, 'scale_pos_weight': 1.1981062753085356, 'grow_policy': 'depthwise', 'max_leaves': 156, 'max_bin': 461}. Best is trial 79 with value: 0.8508718902580795.

Best trial: 79. Best value: 0.850872:  81%|████████  | 81/100 [05:32<01:19,  4.17s/it]

[I 2025-11-24 22:42:56,744] Trial 80 finished with value: 0.8503681314423003 and parameters: {'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.022025116620497748, 'max_delta_step': 7, 'learning_rate': 0.005869206597844647, 'n_estimators': 1189, 'subsample': 0.7111908935977088, 'colsample_bytree': 0.6761286632955481, 'colsample_bylevel': 0.7529333637207163, 'colsample_bynode': 0.6587690065100804, 'reg_alpha': 9.166277314158036, 'reg_lambda': 0.05173332439520235, 'scale_pos_weight': 1.1251742813389196, 'grow_policy': 'lossguide', 'max_leaves': 144, 'max_bin': 484}. Best is trial 79 with value: 0.8508718902580795.

Best trial: 79. Best value: 0.850872:  82%|████████▏ | 82/100 [05:38<01:24,  4.72s/it]

[I 2025-11-24 22:43:02,731] Trial 81 finished with value: 0.8506975122064636 and parameters: {'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.01097703302321152, 'max_delta_step': 7, 'learning_rate': 0.005903961488466101, 'n_estimators': 1198, 'subsample': 0.7132017528376101, 'colsample_bytree': 0.678460366807212, 'colsample_bylevel': 0.752899634387391, 'colsample_bynode': 0.6369232659419587, 'reg_alpha': 9.461777388147842, 'reg_lambda': 0.032875122570487504, 'scale_pos_weight': 1.1902177667729585, 'grow_policy': 'lossguide', 'max_leaves': 154, 'max_bin': 478}. Best is trial 79 with value: 0.8508718902580795.

Best trial: 82. Best value: 0.850939:  83%|████████▎ | 83/100 [05:44<01:27,  5.17s/it]

[I 2025-11-24 22:43:08,968] Trial 82 finished with value: 0.8509390581001834 and parameters: {'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.26487856207123955, 'max_delta_step': 8, 'learning_rate': 0.005712716722773515, 'n_estimators': 1214, 'subsample': 0.713643576397105, 'colsample_bytree': 0.6742469968941949, 'colsample_bylevel': 0.7026895847404427, 'colsample_bynode': 0.6643687761505799, 'reg_alpha': 7.785749125043617, 'reg_lambda': 0.021922525496989653, 'scale_pos_weight': 1.1344056360157786, 'grow_policy': 'lossguide', 'max_leaves': 131, 'max_bin': 483}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  84%|████████▍ | 84/100 [05:48<01:20,  5.04s/it]

[I 2025-11-24 22:43:13,686] Trial 83 finished with value: 0.8497868712702472 and parameters: {'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.2718187530334534, 'max_delta_step': 8, 'learning_rate': 0.011013270402351266, 'n_estimators': 1258, 'subsample': 0.7007540250531913, 'colsample_bytree': 0.6842283857282131, 'colsample_bylevel': 0.6986572455536553, 'colsample_bynode': 0.6141085913954765, 'reg_alpha': 6.9701528312449215, 'reg_lambda': 0.033727940090299544, 'scale_pos_weight': 1.013459134323812, 'grow_policy': 'lossguide', 'max_leaves': 153, 'max_bin': 465}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  85%|████████▌ | 85/100 [05:53<01:15,  5.02s/it]

[I 2025-11-24 22:43:18,676] Trial 84 finished with value: 0.8495130331447466 and parameters: {'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.2895628650147969, 'max_delta_step': 9, 'learning_rate': 0.013169050029865783, 'n_estimators': 1114, 'subsample': 0.7171154923122894, 'colsample_bytree': 0.6628915141497952, 'colsample_bylevel': 0.740637699843693, 'colsample_bynode': 0.6401393993260405, 'reg_alpha': 7.7339921662496005, 'reg_lambda': 0.024028002766862077, 'scale_pos_weight': 1.3097133966193995, 'grow_policy': 'lossguide', 'max_leaves': 134, 'max_bin': 489}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  86%|████████▌ | 86/100 [06:03<01:27,  6.28s/it]

[I 2025-11-24 22:43:27,888] Trial 85 finished with value: 0.8501872949443281 and parameters: {'max_depth': 11, 'min_child_weight': 10, 'gamma': 0.5116370429832875, 'max_delta_step': 7, 'learning_rate': 0.00539886814703971, 'n_estimators': 1329, 'subsample': 0.6912917689364719, 'colsample_bytree': 0.6996070132864792, 'colsample_bylevel': 0.6542199626409745, 'colsample_bynode': 0.6759413548689063, 'reg_alpha': 3.5280139640316093, 'reg_lambda': 0.0337007189109983, 'scale_pos_weight': 1.2227757313107543, 'grow_policy': 'lossguide', 'max_leaves': 159, 'max_bin': 452}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  87%|████████▋ | 87/100 [06:10<01:26,  6.68s/it]

[I 2025-11-24 22:43:35,499] Trial 86 finished with value: 0.849757162417009 and parameters: {'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.25763014596655504, 'max_delta_step': 8, 'learning_rate': 0.00804618306659443, 'n_estimators': 1066, 'subsample': 0.7441038518117385, 'colsample_bytree': 0.661599456595576, 'colsample_bylevel': 0.7216268329647151, 'colsample_bynode': 0.6291292248345481, 'reg_alpha': 6.538647681059421, 'reg_lambda': 0.013321720903393673, 'scale_pos_weight': 1.7312016095346274, 'grow_policy': 'lossguide', 'max_leaves': 131, 'max_bin': 427}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  88%|████████▊ | 88/100 [06:20<01:29,  7.48s/it]

[I 2025-11-24 22:43:44,852] Trial 87 finished with value: 0.8417396471104911 and parameters: {'max_depth': 9, 'min_child_weight': 10, 'gamma': 0.5776303273681781, 'max_delta_step': 7, 'learning_rate': 0.016409520823093215, 'n_estimators': 1192, 'subsample': 0.9337367355193638, 'colsample_bytree': 0.6409822052920578, 'colsample_bylevel': 0.702157233679535, 'colsample_bynode': 0.6903344005260806, 'reg_alpha': 5.57417559411796, 'reg_lambda': 0.06893098855034555, 'scale_pos_weight': 6.245026837407051, 'grow_policy': 'lossguide', 'max_leaves': 147, 'max_bin': 479}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  89%|████████▉ | 89/100 [06:26<01:17,  7.09s/it]

[I 2025-11-24 22:43:51,030] Trial 88 finished with value: 0.8495672840941382 and parameters: {'max_depth': 13, 'min_child_weight': 9, 'gamma': 0.15358716048749768, 'max_delta_step': 9, 'learning_rate': 0.004545855546382698, 'n_estimators': 886, 'subsample': 0.7089206620438464, 'colsample_bytree': 0.7056807794363169, 'colsample_bylevel': 0.7750758064207451, 'colsample_bynode': 0.6084427889440103, 'reg_alpha': 9.905309036749903, 'reg_lambda': 0.023667455604791, 'scale_pos_weight': 1.8645562889251062, 'grow_policy': 'lossguide', 'max_leaves': 154, 'max_bin': 493}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  90%|█████████ | 90/100 [06:38<01:26,  8.69s/it]

[I 2025-11-24 22:44:03,451] Trial 89 finished with value: 0.8431850474049962 and parameters: {'max_depth': 12, 'min_child_weight': 9, 'gamma': 0.4062746084509188, 'max_delta_step': 7, 'learning_rate': 0.00880249716704798, 'n_estimators': 1409, 'subsample': 0.7343996183913435, 'colsample_bytree': 0.6204975552008335, 'colsample_bylevel': 0.7601508155146841, 'colsample_bynode': 0.7274319747764624, 'reg_alpha': 0.011555122847686157, 'reg_lambda': 0.05338625962617289, 'scale_pos_weight': 1.2065108914286848, 'grow_policy': 'lossguide', 'max_leaves': 163, 'max_bin': 443}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  91%|█████████ | 91/100 [06:45<01:13,  8.20s/it]

[I 2025-11-24 22:44:10,523] Trial 90 finished with value: 0.8470213645405461 and parameters: {'max_depth': 11, 'min_child_weight': 10, 'gamma': 0.7995778706512678, 'max_delta_step': 8, 'learning_rate': 0.00986430419481696, 'n_estimators': 774, 'subsample': 0.7295355631739958, 'colsample_bytree': 0.6870948731927861, 'colsample_bylevel': 0.6745566755808771, 'colsample_bynode': 0.6525868655608733, 'reg_alpha': 2.5749679862889887, 'reg_lambda': 0.0071688139933300315, 'scale_pos_weight': 2.0778039097544676, 'grow_policy': 'lossguide', 'max_leaves': 140, 'max_bin': 462}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  92%|█████████▏| 92/100 [06:52<01:01,  7.68s/it]

[I 2025-11-24 22:44:16,985] Trial 91 finished with value: 0.8505192590870341 and parameters: {'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.025558009152843536, 'max_delta_step': 6, 'learning_rate': 0.005924061435990052, 'n_estimators': 1196, 'subsample': 0.7103178344874149, 'colsample_bytree': 0.6748449126240801, 'colsample_bylevel': 0.7365906106168038, 'colsample_bynode': 0.662004520320448, 'reg_alpha': 7.96097735546782, 'reg_lambda': 0.050806685162047706, 'scale_pos_weight': 1.048658132068863, 'grow_policy': 'lossguide', 'max_leaves': 146, 'max_bin': 477}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  93%|█████████▎| 93/100 [07:01<00:57,  8.21s/it]

[I 2025-11-24 22:44:26,435] Trial 92 finished with value: 0.8493864475961663 and parameters: {'max_depth': 10, 'min_child_weight': 10, 'gamma': 0.13056361012045622, 'max_delta_step': 6, 'learning_rate': 0.006054064419316211, 'n_estimators': 1076, 'subsample': 0.6966076917328358, 'colsample_bytree': 0.6760747112167946, 'colsample_bylevel': 0.7115250743947681, 'colsample_bynode': 0.6354700710871766, 'reg_alpha': 4.652600613651223, 'reg_lambda': 0.03956341119889062, 'scale_pos_weight': 1.616340301573306, 'grow_policy': 'lossguide', 'max_leaves': 152, 'max_bin': 500}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  94%|█████████▍| 94/100 [07:06<00:42,  7.07s/it]

[I 2025-11-24 22:44:30,845] Trial 93 finished with value: 0.8504133405667933 and parameters: {'max_depth': 9, 'min_child_weight': 8, 'gamma': 0.4068591886773367, 'max_delta_step': 6, 'learning_rate': 0.005105542967221177, 'n_estimators': 1275, 'subsample': 0.7217232591518852, 'colsample_bytree': 0.6509302592808848, 'colsample_bylevel': 0.7464571956387446, 'colsample_bynode': 0.7188720945214487, 'reg_alpha': 7.815965763336455, 'reg_lambda': 0.019219835883482764, 'scale_pos_weight': 1.4245675680196557, 'grow_policy': 'lossguide', 'max_leaves': 12, 'max_bin': 473}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 82. Best value: 0.850939:  95%|█████████▌| 95/100 [07:09<00:29,  5.84s/it]

[I 2025-11-24 22:44:33,806] Trial 94 finished with value: 0.8483311374615723 and parameters: {'max_depth': 8, 'min_child_weight': 9, 'gamma': 0.3878900944858182, 'max_delta_step': 7, 'learning_rate': 0.0035017100204740794, 'n_estimators': 1237, 'subsample': 0.7203673390567737, 'colsample_bytree': 0.6524743385406977, 'colsample_bylevel': 0.7465477582523354, 'colsample_bynode': 0.66281176365786, 'reg_alpha': 6.9729913439409374, 'reg_lambda': 0.02696123268661558, 'scale_pos_weight': 1.1308484123768852, 'grow_policy': 'lossguide', 'max_leaves': 8, 'max_bin': 452}. Best is trial 82 with value: 0.8509390581001834.

Best trial: 95. Best value: 0.851013:  96%|█████████▌| 96/100 [07:17<00:25,  6.50s/it]

[I 2025-11-24 22:44:41,843] Trial 95 finished with value: 0.8510126843886434 and parameters: {'max_depth': 9, 'min_child_weight': 8, 'gamma': 0.7537914553607383, 'max_delta_step': 10, 'learning_rate': 0.00520964879173031, 'n_estimators': 1280, 'subsample': 0.6862913812669756, 'colsample_bytree': 0.6638660546347694, 'colsample_bylevel': 0.7336502387307278, 'colsample_bynode': 0.6989921711792295, 'reg_alpha': 5.027709128764859, 'reg_lambda': 0.018694374877908836, 'scale_pos_weight': 1.391115248420587, 'grow_policy': 'lossguide', 'max_leaves': 30, 'max_bin': 477}. Best is trial 95 with value: 0.8510126843886434.

Best trial: 95. Best value: 0.851013:  97%|█████████▋| 97/100 [07:25<00:20,  6.97s/it]

[I 2025-11-24 22:44:49,919] Trial 96 finished with value: 0.8492637371153996 and parameters: {'max_depth': 10, 'min_child_weight': 9, 'gamma': 0.1827119054183002, 'max_delta_step': 10, 'learning_rate': 0.007198409011150695, 'n_estimators': 1034, 'subsample': 0.6695701572848856, 'colsample_bytree': 0.6420813172457703, 'colsample_bylevel': 0.730584057645177, 'colsample_bynode': 0.6742479770352642, 'reg_alpha': 3.1688084334494415, 'reg_lambda': 0.014412668457448352, 'scale_pos_weight': 1.035371296792842, 'grow_policy': 'lossguide', 'max_leaves': 52, 'max_bin': 457}. Best is trial 95 with value: 0.8510126843886434.

Best trial: 95. Best value: 0.851013:  98%|█████████▊| 98/100 [07:31<00:13,  6.86s/it]

[I 2025-11-24 22:44:56,521] Trial 97 finished with value: 0.8504611330698286 and parameters: {'max_depth': 9, 'min_child_weight': 9, 'gamma': 0.8929054248544588, 'max_delta_step': 9, 'learning_rate': 0.004330782904065715, 'n_estimators': 1137, 'subsample': 0.6866589654365732, 'colsample_bytree': 0.6634596941678506, 'colsample_bylevel': 0.6822597714438147, 'colsample_bynode': 0.6458048729679129, 'reg_alpha': 4.946612288460817, 'reg_lambda': 0.012309193334438097, 'scale_pos_weight': 1.3398252063032565, 'grow_policy': 'lossguide', 'max_leaves': 115, 'max_bin': 496}. Best is trial 95 with value: 0.8510126843886434.

Best trial: 95. Best value: 0.851013:  99%|█████████▉| 99/100 [07:40<00:07,  7.54s/it]

[I 2025-11-24 22:45:05,645] Trial 98 finished with value: 0.8498656643157921 and parameters: {'max_depth': 9, 'min_child_weight': 9, 'gamma': 0.9548645930057094, 'max_delta_step': 10, 'learning_rate': 0.004067026686433043, 'n_estimators': 1130, 'subsample': 0.6883110694194516, 'colsample_bytree': 0.6690432469253862, 'colsample_bylevel': 0.7097993952056927, 'colsample_bynode': 0.6471313712692118, 'reg_alpha': 1.9130557046552674, 'reg_lambda': 0.01145006533722342, 'scale_pos_weight': 1.3754360527168326, 'grow_policy': 'lossguide', 'max_leaves': 39, 'max_bin': 510}. Best is trial 95 with value: 0.8510126843886434.

Best trial: 95. Best value: 0.851013: 100%|██████████| 100/100 [07:53<00:00,  4.73s/it]

[I 2025-11-24 22:45:17,809] Trial 99 finished with value: 0.8491694437985997 and parameters: {'max_depth': 9, 'min_child_weight': 10, 'gamma': 0.8142909751372156, 'max_delta_step': 9, 'learning_rate': 0.0031043642395081382, 'n_estimators': 1312, 'subsample': 0.6507757087521114, 'colsample_bytree': 0.6206994191396439, 'colsample_bylevel': 0.6607216641650279, 'colsample_bynode': 0.7008615671670254, 'reg_alpha': 0.06020981206808512, 'reg_lambda': 0.005252129274238226, 'scale_pos_weight': 1.9262666951007783, 'grow_policy': 'lossguide', 'max_leaves': 76, 'max_bin': 496}. Best is trial 95 with value: 0.8510126843886434.
==================================================
OPTIMIZATION RESULTS
==================================================

Best AUC: 0.8510

Best hyperparameters:
  max_depth: 9
  min_child_weight: 8
  gamma: 0.7537914553607383
  max_delta_step: 10
  learning_rate: 0.00520964879173031
  n_estimators: 1280
  subsample: 0.6862913812669756
  colsample_bytree: 0.6638660546347694
  colsample_bylevel: 0.7336502387307278
  colsample_bynode: 0.6989921711792295
  reg_alpha: 5.027709128764859
  reg_lambda: 0.018694374877908836
  scale_pos_weight: 1.391115248420587
  grow_policy: lossguide
  max_leaves: 30
  max_bin: 477

Best trial metrics:
  Accuracy:  0.7991
  Precision: 0.6213
  Recall:    0.6230
  F1 Score:  0.6222
  AUC:       0.8510

==================================================
TOP 5 TRIALS BY ACCURACY
==================================================
    number  user_attrs_accuracy  user_attrs_precision  user_attrs_recall  \
91      91             0.811214              0.682432           0.540107
94      94             0.809084              0.664577           0.566845
6        6             0.807665              0.660436           0.566845
13      13             0.806955              0.663462           0.553476
82      82             0.806246              0.657321           0.564171

    user_attrs_f1     value
91       0.602985  0.850519
94       0.611833  0.848331
6        0.610072  0.846259
13       0.603499  0.849363
82       0.607194  0.850939

In [191]:
# Train final model with best parameters
best_model = xgb.XGBClassifier(**study.best_params, random_state=42)
best_model.fit(X_train_transformed, y_train_encoded)

# Make predictions
y_pred_proba = best_model.predict_proba(X_test_transformed)[:, 1]
y_pred = best_model.predict(X_test_transformed)

print("\n" + "=" * 50)
print("FINAL MODEL EVALUATION")
print("=" * 50)
print(f"\nAccuracy:  {accuracy_score(y_test_encoded, y_pred):.4f}")
print(f"Precision: {precision_score(y_test_encoded, y_pred):.4f}")
print(f"Recall:    {recall_score(y_test_encoded, y_pred):.4f}")
print(f"F1 Score:  {f1_score(y_test_encoded, y_pred):.4f}")
print(f"AUC:       {roc_auc_score(y_test_encoded, y_pred_proba):.4f}")

==================================================
FINAL MODEL EVALUATION
==================================================

Accuracy:  0.7991
Precision: 0.6213
Recall:    0.6230
F1 Score:  0.6222
AUC:       0.8510

### Note on Accuracy vs AUC

**Important**: 72% accuracy might actually be good for churn prediction! Here's why:

1. **Class imbalance**: If 73% of customers don't churn, a model predicting "No churn" for everyone gets 73% accuracy but is useless
2. **Business value**: It's better to correctly identify churners (high recall) than overall accuracy
3. **90% accuracy is unrealistic** for most real-world churn datasets

**If you still want to optimize for accuracy:**
- Change `return auc` to `return accuracy` in the objective function above
- But be aware this might hurt the model's ability to identify actual churners

**Better approach**: Focus on F1-score or recall for churners, not raw accuracy

In [192]:
# Save the best model
with open('../best_xgboost_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

print("\n✅ Model saved as 'best_xgboost_model.pkl'")

✅ Model saved as 'best_xgboost_model.pkl'

### Why AUC instead of Accuracy, Precision, or Recall?

**AUC (Area Under ROC Curve)** is often preferred for binary classification, especially with imbalanced datasets:

1. **Threshold-independent**: AUC measures performance across all classification thresholds, not just one
2. **Handles class imbalance**: Works well even when classes are imbalanced (churn is typically minority class)
3. **Balanced metric**: Considers both true positive rate and false positive rate
4. **Business value**: Shows model's ability to rank customers by churn probability

**When to use each metric:**
- **Accuracy**: When classes are balanced and false positives/negatives have equal cost
- **Precision**: When false positives are costly (e.g., spam detection - don't want to mark real emails as spam)
- **Recall**: When false negatives are costly (e.g., disease detection - don't want to miss sick patients)
- **AUC**: When you want overall ranking ability and threshold flexibility

For churn prediction, **AUC is ideal** because:
- We want to identify high-risk customers (ranking matters)
- Business can adjust threshold based on retention campaign capacity
- Class imbalance is common (more non-churners than churners)